// LDC1 DPS MANAGER V183_SERVICE_LOCKED_REG_REFRESH
// Paste into Space Engineers Programmable Block. No namespace/usings/wrapper.

const string VERSION="LDC1_DPS_V183_ServiceLockedRegRefresh";
const string DEF_TAG="[LDC1]",SYS="[DPS]",NO="[NODPS]";
const string DCS_SVC_BEGIN="# <DCS_SERVICE_BEGIN>",DCS_SVC_END="# <DCS_SERVICE_END>";
const int MAXB=20,MAXS=12,APPLY_MAX=30;
const int LS_IDLE=0,LS_FAULT=1,LS_PRINT=2,LS_READY=3,LS_LAUNCH=4,LS_SETUP=5,LS_STOPPED=6,LS_COMPLETE=7;
const double ROTOR_RPM=5.0,ROTOR_TARGET_DEG=0.0; const int ROTOR_ALIGN_TIMEOUT_TICKS=8,PRINT_STALL_TICKS=180,PRINT_PJ_WAIT_TICKS=60;
const double SENSOR_COMMISSION_MAX_M=25.0,SENSOR_COMMISSION_GAP_M=2.0,SENSOR_FRONT_EXTRA_M=2.0,SENSOR_FRONT_SANITY_MIN_M=2.0,SENSOR_FRONT_SANITY_MAX_M=11.0;
const float SENSOR_BACK_M=.10f,SENSOR_SIDE_M=.75f,SENSOR_TOP_M=1f,SENSOR_BOTTOM_M=1f;
string Tag=DEF_TAG;
bool AutoOn=true,Paused=false,Recheck=false,EntityAuth=false,ReviewPause=false;
int RefreshSec=10,Tick=0,Hi=0,HiCap=0,ManagedBays=10; double DoorCloseDelaySec=10,DtSec=0; string HiPhase="INIT",HiCapPhase="INIT",Mode="IDLE",Status="Idle",ExpectedHardware="W12 G2 PJ1+ MG1 CN1 O1";
string LastState="IDLE";int LastBays=0,LastDmg=0,LastDst=0,LastPJ=0,LastLI=0,LastLX=0; int[] FastLS=new int[MAXB+1];
string[] SR=new string[MAXS+1],SL=new string[MAXS+1],SS=new string[MAXS+1];
int[] Sel=new int[MAXB+1],SlotMask=new int[MAXB+1],PrintSlot=new int[MAXB+1],ReadySlot=new int[MAXB+1],LoadedSlot=new int[MAXB+1],BayState=new int[MAXB+1],LastRemain=new int[MAXB+1],StallTicks=new int[MAXB+1]; double[] LaunchSec=new double[MAXB+1]; int[] LaunchPhase=new int[MAXB+1]; bool[] BayStopped=new bool[MAXB+1]; int SetupBay=0,SetupSlot=0,ShowSlot=0;
bool RotAlignRun=false; int RotAlignTick=0,RotAlignSeen=0,RotAlignLocked=0,RotAlignMoving=0;
Bay[] B,LiveB,BuildB;
bool[] Reg=new bool[MAXB+1]; long[] RegGrid=new long[MAXB+1]; Vector3D[] RegMin=new Vector3D[MAXB+1],RegMax=new Vector3D[MAXB+1];
List<IMyTerminalBlock> All=new List<IMyTerminalBlock>();
List<IMyTerminalBlock> TW=new List<IMyTerminalBlock>(),TD=new List<IMyTerminalBlock>(),TP=new List<IMyTerminalBlock>(),TM=new List<IMyTerminalBlock>(),TC=new List<IMyTerminalBlock>(),TA=new List<IMyTerminalBlock>(),TN=new List<IMyTerminalBlock>(),TS=new List<IMyTerminalBlock>();
List<IMyLightingBlock> Lights=new List<IMyLightingBlock>();
List<IMyTextPanel> Panels=new List<IMyTextPanel>();
List<IMyTextPanel> HelmLcds=new List<IMyTextPanel>();
List<IMyProgrammableBlock> PbTmp=new List<IMyProgrammableBlock>(); IMyProgrammableBlock DcsPb=null; int[] DcsSvcSeen=new int[MAXB+1]; string DcsRegRefresh="NONE";
List<DCl> DClus=new List<DCl>(); string PvAnchor="",PvNum="",PvPlan="",PvSupport="",PvAccept="",PvLight="",PvFoot=""; string BayNumbering="SEQUENTIAL",RefTag="[DPS_REF]"; double LiExtra=0,LxGate=2.5; IMyTerminalBlock RefBlock=null;
bool DiscRun=false,DiscCommission=false,DiscAccept=false,DiscLights=false,DiscPrevPaused=false,DiscPrevAuto=false; int DiscStage=0,DiscIdx=0,DiscHi=0,D_ep=0,D_wg=0,D_wr=0,D_pg=0,D_pr=0,D_bs=0,D_bm=0,D_bc=0,D_bp=0,D_bo=0,D_rv=0,D_rm=0,D_rc=0,D_rp=0,D_ro=0,D_sSafe=0,D_sCheck=0,D_safe=0,D_remap=0,D_check=0,D_ren=0,D_occ=0,D_best=0,D_agree=0,LIdx=0,LSkip=0; string D_conf="",DiscHiPhase=""; int[] LLI=new int[MAXB+1],LLX=new int[MAXB+1]; int LASeen=0;
Queue<RenameJob> Q=new Queue<RenameJob>();
bool ApplyRun=false,ApplyScanAfter=false,AccRun=false; int ApplyTotal=0,ApplyDone=0,AccIdx=0,AccBay=1,AccJobs=0; string ApplyTitle="";
bool ScanRun=false,ScanAuto=false,ScanForce=false;
int ScanStage=0,ScanIdx=0,GateIdx=0,LightIdx=0,PanelIdx=0;

public Program(){Init();LoadCfg();LockDpsRotors(false);SetRunFreq();}
public void Save(){}
public void Main(string arg,UpdateType src){Hi=0;HiPhase="START";DtSec=Runtime.TimeSinceLastRun.TotalSeconds;if(DtSec<0||DtSec>5)DtSec=0;Upd("MAIN");if(arg!=null&&arg.Trim().Length>0)Cmd(arg.Trim());else{if((src&UpdateType.Update10)!=0){RotorAlignStep();FeedbackLane();}if((src&UpdateType.Update100)!=0)Auto();}EchoOut();Upd("END");}

void Init(){LiveB=new Bay[MAXB+1];BuildB=new Bay[MAXB+1];for(int i=0;i<=MAXB;i++){LiveB[i]=new Bay(i);BuildB[i]=new Bay(i);FastLS[i]=-1;BayState[i]=LS_IDLE;LastRemain[i]=-1;}B=LiveB;for(int i=1;i<=MAXB;i++)Sel[i]=1;SlotDef();}
void SlotDef(){for(int i=0;i<=MAXS;i++){SR[i]="";SL[i]="";SS[i]="";}SR[1]="MISSILE";SL[1]="MISSILE";SS[1]="MSL";SR[2]="INTERCEPTOR";SL[2]="INTERCEPTOR";SS[2]="INT";SR[3]="DEFENDER";SL[3]="DEFENDER";SS[3]="DEF";}
void Upd(string p){int n=Runtime.CurrentInstructionCount;if(n>Hi){Hi=n;HiPhase=p;}if(n>HiCap){HiCap=n;HiCapPhase=p;}}
void SetRunFreq(){UpdateFrequency f=UpdateFrequency.None;if(AutoOn&&!Paused)f|=UpdateFrequency.Update10|UpdateFrequency.Update100;if(RotAlignRun)f|=UpdateFrequency.Update10;if(ScanRun||DiscRun||ApplyRun||AccRun)f|=UpdateFrequency.Update100;Runtime.UpdateFrequency=f;}
void DUpd(string p){Upd(p);if(Hi>DiscHi){DiscHi=Hi;DiscHiPhase=p;}}
bool DetectEntityAuthorityFromAll(){for(int i=0;i<All.Count;i++){IMyProgrammableBlock pb=All[i] as IMyProgrammableBlock;if(IsEntityAuthority(pb))return true;}return false;}
bool RefreshEntityAuthority(){List<IMyProgrammableBlock> pbs=new List<IMyProgrammableBlock>();GridTerminalSystem.GetBlocksOfType<IMyProgrammableBlock>(pbs);for(int i=0;i<pbs.Count;i++)if(IsEntityAuthority(pbs[i])){EntityAuth=true;return true;}EntityAuth=false;return false;}
bool IsEntityAuthority(IMyProgrammableBlock pb){if(pb==null||Ex(pb)||Foreign(pb.CustomName))return false;string cd=pb.CustomData;string t=Val(cd,"Tag=");if(t!=Tag)return false;return Has(pb.CustomName,"ARGOS")||Has(cd,"ARGOS")||Has(cd,"[AUTOTAG]");}
bool RenameAllowed(IMyTerminalBlock b){if(b==null||Ex(b)||Foreign(b.CustomName))return false;if(Has(b.CustomName,Tag))return true;return EntityAuth;}

void Cmd(string a){string u=a.ToUpper();Mode="CMD";Status="Command "+a;if(u.StartsWith("LAUNCH ")){DoLaunch(u,a);return;}if(u=="STOP"||u=="STOP ALL"||u.StartsWith("STOP BAY")){DoStop(u,a);return;}if(u=="CLEAR"||u=="CLEAR ALL"||u.StartsWith("CLEAR BAY")){DoClear(u,a);return;}if(u.StartsWith("PRINT ")){DoPrint(u,a);return;}if(u=="AUTO"||u=="AUTO ON"){ReviewPause=false;AutoOn=true;Paused=false;SetRunFreq();Status="AUTO ON";CommandReport("AUTO ON","Automatic DPS maintenance enabled.");return;}if(u=="AUTO OFF"){ReviewPause=false;AutoOn=false;Paused=true;ScanRun=false;DiscRun=false;SetRunFreq();Status="AUTO OFF";CommandReport("AUTO OFF","Automatic DPS maintenance disabled by command.");return;}if(u=="DISCOVER"||u=="DRYRUN"){BeginDiscover(false,false,false);return;}if(u=="COMMISSION DRYRUN"){BeginDiscover(true,false,false);return;}if(u=="COMMISSION ACCEPT"){ClearReviewPause();BeginDiscover(true,true,false);return;}if(u=="COMMISSION LIGHTS DRYRUN"){BeginDiscover(true,false,true);return;}if(u=="COMMISSION LIGHTS ACCEPT"){ClearReviewPause();BeginDiscover(true,true,true);return;}if(u=="STATUS"){ClearReviewPause();BeginScanReport(false,true);return;}if(u=="ROTOR ALIGN"){StartRotorAlign(a);return;}if(u=="PROJECTOR NAMES"||u=="CLEAN PROJECTOR NAMES"){DoProjectorNames(a);return;}if(u=="SETUP OFF"||u=="SHOW OFF"){DoSetupOff(a);return;}if(u.StartsWith("SETUP ACCEPT")){DoSetupAccept(u,a);return;}if(u.StartsWith("SETUP BAY")){LoadCfg();int b=BayNum(u),s=SlotAfterBay(u);if(b>0&&s>0)DoSetup(b,s,a);else Status="SETUP needs BAY## and PJ##";return;}if(u.StartsWith("SHOW ")){LoadCfg();int s=SlotFrom(u.Substring(5).Trim());if(s>0)DoShow(s,a);else Status="SHOW needs PJ##/slot";return;}if(u.StartsWith("SELECT ALL ")){LoadCfg();int s=SlotFrom(u.Substring(11).Trim());if(s>0)DoSelect(0,s,a);return;}if(u.StartsWith("SELECT BAY")){LoadCfg();int b=BayNum(u),s=SlotAfterBay(u);if(b>0&&s>0)DoSelect(b,s,a);return;}Status="Unknown command";}
void ClearReviewPause(){if(ReviewPause){ReviewPause=false;if(AutoOn)Paused=false;}}
void Auto(){if(DiscRun){DiscoverStep();return;}if(AccRun){AcceptQueueStep();return;}if(ApplyRun){ApplyStep();return;}if(ScanRun){ScanStep();return;}if(Paused||!AutoOn)return;if(Recheck){Recheck=false;BeginScanReport(true,true);return;}Tick++;int t=RefreshSec<=0?1:Math.Max(1,RefreshSec/10);if(Tick>=t){Tick=0;BeginScanReport(true,false);}}


void BeginScanReport(bool auto,bool force){B=BuildB;Clear();ScanAuto=auto;ScanForce=force;ScanRun=true;ScanStage=0;ScanIdx=GateIdx=LightIdx=PanelIdx=0;Tick=0;SetRunFreq();Status=(auto?"Auto scan queued":"Status scan queued");}
void ScanStep(){if(ScanStage==0){Mode=ScanAuto?"AUTO":"STATUS";B=BuildB;LoadCfg();All.Clear();Lights.Clear();Panels.Clear();HelmLcds.Clear();DcsPb=null;TW.Clear();TD.Clear();TP.Clear();TM.Clear();TC.Clear();TA.Clear();TN.Clear();TS.Clear();GridTerminalSystem.GetBlocksOfType<IMyTerminalBlock>(All);EntityAuth=DetectEntityAuthorityFromAll();ScanIdx=0;ScanStage=1;Upd("SCAN ALL");return;}if(ScanStage==1){while(ScanIdx<All.Count&&Runtime.CurrentInstructionCount<22000){IMyTerminalBlock x=All[ScanIdx++];if(x==null||Ex(x))continue;IMyProgrammableBlock pbx=x as IMyProgrammableBlock;if(pbx!=null&&pbx!=Me&&Has(pbx.CustomName,Tag)&&Has(pbx.CustomName,"[DCS]"))DcsPb=pbx;IMyLightingBlock l=x as IMyLightingBlock;if(l!=null&&!Has(x.CustomName,SYS))Lights.Add(l);IMyTextPanel pnl=x as IMyTextPanel;if(pnl!=null)Panels.Add(pnl);if(x is IMyShipWelder)TW.Add(x);else if(x is IMyDoor)TD.Add(x);else if(x is IMyProjector)TP.Add(x);else if(x is IMyShipMergeBlock)TM.Add(x);else if(x is IMyShipConnector)TC.Add(x);else if(x is IMyCameraBlock)TA.Add(x);else if(x is IMySensorBlock)TN.Add(x);else if(x is IMyMotorStator)TS.Add(x);int b=BayNum(x.CustomName);if(b<1||b>MAXB)continue;bool tagged=Has(x.CustomName,SYS)||Has(x.CustomName,"[BAY");if(!Has(x.CustomName,Tag)&&!tagged)continue;RoleScan(x,b);}Upd("SCAN TYPED");if(ScanIdx<All.Count)return;ScanStage=2;return;}if(ScanStage==2){BuildBounds();UpdateReg();ConfigLaunchSensorsAll();GateIdx=LightIdx=PanelIdx=0;ScanStage=3;Upd("SCAN BOUNDS");return;}if(ScanStage==3){while(GateIdx<TD.Count&&Runtime.CurrentInstructionCount<22000){IMyDoor d=TD[GateIdx++] as IMyDoor;if(d!=null&&!Ex(d))GateCheck(d);}if(GateIdx<TD.Count)return;while(LightIdx<Lights.Count&&Runtime.CurrentInstructionCount<22000)LightCheck(Lights[LightIdx++]);if(LightIdx<Lights.Count)return;while(PanelIdx<Panels.Count&&Runtime.CurrentInstructionCount<22000)PanelCheck(Panels[PanelIdx++]);Upd("SCAN ACCESSORY");if(PanelIdx<Panels.Count)return;ScanStage=4;return;}if(ScanStage==4){if(AutoOn&&!Paused)EnforcePj(false);RefreshFaults();AutoHeal();if(!RotAlignRun)LockDpsRotors(false);if(Q.Count>0){ApplyJobs();Recheck=true;}Report(ScanForce);CommitScanBuild();ScanRun=false;SetRunFreq();Status="Scan complete";}}

void Clear(){for(int i=1;i<=MAXB;i++)B[i].Clr();Q.Clear();}
void CommitScanBuild(){Bay[] old=LiveB;LiveB=BuildB;BuildB=old;B=LiveB;for(int i=0;i<=MAXB;i++)FastLS[i]=-1;}
void RoleScan(IMyTerminalBlock x,int b){Bay y=B[b];IMyCubeBlock c=x as IMyCubeBlock;if(x is IMyShipWelder){y.W++;y.Wls.Add(x as IMyShipWelder);y.AddW(c);Bad(y,x,"W");}
 else if(x is IMyDoor){y.G++;y.Gates.Add(x as IMyDoor);Bad(y,x,"G");}
 else if(x is IMyProjector){IMyProjector pj=x as IMyProjector;KeepPj(pj);y.P++;y.Pjs.Add(pj);Bad(y,x,"P");}
 else if(x is IMyShipMergeBlock){y.M++;y.Ms.Add(x as IMyShipMergeBlock);Bad(y,x,"M");}
 else if(x is IMyShipConnector){y.C++;IMyShipConnector cn=x as IMyShipConnector;y.Cs.Add(cn);Bad(y,x,"C");}
 else if(x is IMySensorBlock){y.A++;IMySensorBlock sn=x as IMySensorBlock;y.Sens.Add(sn);Bad(y,x,"A");} 
 else if(x is IMyCameraBlock){y.A++;IMyCameraBlock cam=x as IMyCameraBlock;y.As.Add(cam);Bad(y,x,"A");}
 else if(x is IMyMotorStator){y.S++;Bad(y,x,"S");}
 else if(x is IMyTextPanel){IMyTextPanel p=x as IMyTextPanel;if(p!=null)y.Lcds.Add(p);}
 else if(x is IMyLightingBlock){IMyLightingBlock lt=x as IMyLightingBlock;if(lt!=null)y.Lts.Add(lt);RoleLight(y,x);}}
void RoleLight(Bay y,IMyTerminalBlock x){string n=x.CustomName.ToUpper();IMyCubeBlock c=x as IMyCubeBlock;bool bad=c!=null&&!c.IsFunctional;if(Has(n,"LX")||Has(n,"EXTERIOR")){y.XG++;if(bad){y.Dmg++;y.DLG++;}}else if(Has(n,"LG")){y.LG++;if(bad){y.Dmg++;y.DLG++;}}else{y.LI++;if(bad){y.Dmg++;y.DLI++;}}}
void GateCheck(IMyDoor d){if(Has(d.CustomName,SYS))return;if(Foreign(d.CustomName))return;IMyCubeBlock cb=d as IMyCubeBlock;if(cb==null)return;Vector3D p=LP(cb);for(int i=1;i<=MAXB;i++){Bay y=B[i];if(y.Ready&&y.Core()&&InBox(y,p,0.05,false)){y.XG++;return;}}}
void LightCheck(IMyLightingBlock l){if(Foreign(l.CustomName)||Ex(l))return;IMyCubeBlock cb=l as IMyCubeBlock;if(cb==null)return;Vector3D p=LP(cb);Bay bi=FindLightBay(cb,p,true),bg=FindLightBay(cb,p,false);if(bi!=null&&bg!=null&&bi.N!=bg.N)return;bool bad=!cb.IsFunctional;if(bi!=null){bi.LI++;if(bad){bi.Dmg++;bi.DLI++;}}else if(bg!=null){bg.LG++;if(bad){bg.Dmg++;bg.DLG++;}}}
Bay FindLightBay(IMyCubeBlock cb,Vector3D p,bool inner){Bay best=null;double bs=999999,ss=999999;for(int i=1;i<=MAXB;i++){Bay y=B[i];if(!y.Ready||!y.Core()||cb.CubeGrid!=y.Grid)continue;bool inside=inner?InBox(y,p,0.05,true):InOut(y,p);if(!inside)continue;double d=Math.Abs(Axis(p,y.BayAxis)-Axis(y.Ctr,y.BayAxis));if(d<bs){ss=bs;bs=d;best=y;}else if(d<ss)ss=d;}if(best!=null&&ss-bs<0.25)return null;return best;}
void PanelCheck(IMyTextPanel p){if(p==null||Ex(p)||Foreign(p.CustomName))return;IMyCubeBlock cb=p as IMyCubeBlock;if(cb==null)return;Bay y=FindPanelBay(cb);if(y!=null){int n=0;for(int i=0;i<y.Lcds.Count;i++)if(y.Lcds[i]==p){n=i+1;break;}if(n<1){y.Lcds.Add(p);n=y.Lcds.Count;}QR(p,LcdName(y.N,n));return;}if(IsHelmLcd(p))HelmLcds.Add(p);}
Bay FindPanelBay(IMyCubeBlock cb){if(cb==null)return null;Bay best=null;double bd=999999,sd=999999;for(int i=1;i<=MAXB;i++){Bay y=B[i];if(y==null||!y.Core())continue;bool ok=false;if(RegDock(y,cb,8.0))ok=true;else if(y.Ready&&cb.CubeGrid==y.Grid){Vector3D p=LP(cb);ok=InBox(y,p,2.0,true)||InOut(y,p);}if(!ok)continue;Vector3D c=Reg[i]?((RegMin[i]+RegMax[i])/2):y.Ctr;double d=Vector3D.DistanceSquared(LP(cb),c);if(d<bd){sd=bd;bd=d;best=y;}else if(d<sd)sd=d;}if(best!=null&&sd-bd<0.25)return null;return best;}
void BuildBounds(){for(int i=1;i<=MAXB;i++)B[i].Bounds();PickAxes();}
void PickAxes(){double minx=0,maxx=0,miny=0,maxy=0,minz=0,maxz=0,sx=0,sy=0,sz=0;int n=0;bool any=false;for(int i=1;i<=MAXB;i++)if(B[i].Ready){Vector3D c=B[i].Ctr;if(!any){minx=maxx=c.X;miny=maxy=c.Y;minz=maxz=c.Z;any=true;}else{minx=Math.Min(minx,c.X);maxx=Math.Max(maxx,c.X);miny=Math.Min(miny,c.Y);maxy=Math.Max(maxy,c.Y);minz=Math.Min(minz,c.Z);maxz=Math.Max(maxz,c.Z);}sx+=c.X;sy+=c.Y;sz+=c.Z;n++;}if(n==0)return;double rx=maxx-minx,ry=maxy-miny,rz=maxz-minz;int bay=2;if(rx>=ry&&rx>=rz)bay=0;else if(ry>=rx&&ry>=rz)bay=1;double bx=bay==0?-1:rx,by=bay==1?-1:ry,bz=bay==2?-1:rz;int outa=1;if(bx>=by&&bx>=bz)outa=0;else if(by>=bx&&by>=bz)outa=1;else outa=2;double center=outa==0?sx/n:(outa==1?sy/n:sz/n);for(int i=1;i<=MAXB;i++)if(B[i].Ready){B[i].BayAxis=bay;B[i].OutAxis=outa;B[i].CenterLine=center;}}
void RefreshFaults(){for(int i=1;i<=MAXB;i++){Bay y=B[i];if(!y.Core())continue;if(y.W<12)y.Miss+=12-y.W;if(y.G<2)y.Miss+=2-y.G;int mask=ExpectedSlotMask(y);for(int s=1;s<=MAXS;s++)if(SlotBit(mask,s)&&!BayHasSlot(y,s))y.Miss++;if(y.M<1)y.Miss++;if(y.C<1)y.Miss++;if(y.A<1)y.Miss++;for(int p=0;p<y.Pjs.Count;p++){IMyFunctionalBlock f=y.Pjs[p] as IMyFunctionalBlock;int sl=PjSlot(y.Pjs[p]);bool want=WantPjOn(i,sl);if(f!=null&&f.Enabled!=want)y.PCtl++;}}}
int ConfigSlotCount(){int n=0;for(int i=1;i<=MAXS;i++)if(SR[i]!="")n++;return n;}
int ExpectedSlotMask(Bay y){if(y==null)return 0;int m=SlotMask[y.N];return m!=0?m:SlotMaskFromBay(y);}
int SlotMaskFromBay(Bay y){int m=0;if(y==null)return 0;for(int i=0;i<y.Pjs.Count;i++){int s=PjSlot(y.Pjs[i]);if(s>0&&s<=MAXS)m|=1<<(s-1);}return m;}
bool SlotBit(int m,int s){return s>0&&s<=MAXS&&(m&(1<<(s-1)))!=0;}
void Bad(Bay y,IMyTerminalBlock x,string r){IMyCubeBlock c=x as IMyCubeBlock;if(c==null||c.IsFunctional)return;y.Dmg++;if(r=="W")y.DW++;else if(r=="G")y.DG++;else if(r=="P")y.DP++;else if(r=="M")y.DM++;else if(r=="C")y.DC++;else if(r=="A")y.DA++;else if(r=="S")y.DS++;}

void EnforcePj(bool force){for(int i=1;i<=MAXB;i++){Bay y=B[i];for(int p=0;p<y.Pjs.Count;p++){IMyProjector pj=y.Pjs[p];KeepPj(pj);int s=PjSlot(pj);bool want=WantPjOn(i,s);IMyFunctionalBlock f=pj as IMyFunctionalBlock;if(f!=null&&f.Enabled!=want)f.Enabled=want;}}}

void DoPrint(string u,string arg){LoadCfg();PrintTarget t=ParsePrint(u);if(!t.Ok){CommandReport("PRINT",t.Msg);return;}SetupBay=0;SetupSlot=0;ShowSlot=0;int ab=ActBays(),set=0,skip=0,fault=0;int a=t.All?1:t.Bay,z=t.All?ab:t.Bay;for(int b=a;b<=z&&b<=MAXB;b++){int sl=t.Slot>0?t.Slot:Sel[b];if(sl<1){skip++;continue;}if(!BaySlotAvailable(b,sl)){skip++;continue;}Bay y=LiveB!=null?LiveB[b]:null;if(y!=null&&(y.Miss>0||y.PCtl>0||FastBayFault(y))){fault++;continue;}PrintSlot[b]=sl;LoadedSlot[b]=sl;ReadySlot[b]=0;BayStopped[b]=false;BayState[b]=LS_PRINT;LastRemain[b]=-1;StallTicks[b]=0;set++;}int[] r=ApplyPjModeScan();ApplyPrintWeldersScan(0);ResetFastLS();FeedbackOnce();Status="PRINT set "+set+" skip "+skip+" fault "+fault;SetPrintReport(arg,"PRINT",set,skip,fault,r);PersistCfg();SetRunFreq();}
class PrintTarget{public bool Ok,All;public int Bay,Slot;public string Msg;}
PrintTarget ParsePrint(string u){PrintTarget t=new PrintTarget();t.Msg="PRINT syntax: PRINT ALL [PJ##|SELECTED], PRINT BAY## [PJ##|SELECTED], PRINT SELECTED";string[] p=u.Split(new char[]{' '},StringSplitOptions.RemoveEmptyEntries);if(p.Length<2||p[0]!="PRINT")return t;int idx=1;if(p[idx]=="SELECTED"){t.All=true;t.Slot=0;t.Ok=true;return t;}if(p[idx]=="ALL"){t.All=true;idx++;}else if(p[idx].StartsWith("BAY")){t.Bay=BayNum(p[idx]);if(t.Bay<1)return t;idx++;}else return t;if(idx<p.Length){if(p[idx]=="SELECTED")t.Slot=0;else t.Slot=SlotFrom(p[idx]);if(t.Slot<0)return t;if(t.Slot==0&&p[idx]!="SELECTED")return t;idx++;}if(idx!=p.Length)return t;t.Ok=true;return t;}
void DoStop(string u,string arg){int bay=BayNum(u);bool all=(bay<1);int a=all?1:bay,z=all?ActBays():bay;int stopped=0;for(int b=a;b<=z&&b<=MAXB;b++){BayStopped[b]=true;PrintSlot[b]=0;ReadySlot[b]=0;BayState[b]=LS_STOPPED;LastRemain[b]=-1;StallTicks[b]=0;LaunchSec[b]=0;LaunchPhase[b]=0;stopped++;}if(all){SetupBay=0;SetupSlot=0;ShowSlot=0;}else if(SetupBay==bay){SetupBay=0;SetupSlot=0;}StopHardwareScan(bay);ResetFastLS();FeedbackOnce();Status="STOP "+(all?"ALL":"BAY"+B2(bay));CommandReport("STOP",(all?"All bays":"BAY"+B2(bay))+" stopped. Welders/projectors forced off immediately. Use CLEAR to release stopped state.");SetRunFreq();}
void DoClear(string u,string arg){int bay=BayNum(u);bool all=(bay<1);int a=all?1:bay,z=all?ActBays():bay;for(int b=a;b<=z&&b<=MAXB;b++){BayStopped[b]=false;PrintSlot[b]=0;ReadySlot[b]=0;LoadedSlot[b]=0;BayState[b]=LS_IDLE;LastRemain[b]=-1;StallTicks[b]=0;LaunchSec[b]=0;LaunchPhase[b]=0;}if(all){SetupBay=0;SetupSlot=0;ShowSlot=0;}else if(SetupBay==bay){SetupBay=0;SetupSlot=0;}ApplyPjModeScan();ApplyPrintWeldersScan(bay);CloseBayDoorsScan(bay);ResetFastLS();FeedbackOnce();Status="CLEAR "+(all?"ALL":"BAY"+B2(bay));CommandReport("CLEAR",(all?"All bays":"BAY"+B2(bay))+" released to normal idle/fault evaluation.");SetRunFreq();}
void SetPrintReport(string arg,string mode,int set,int skip,int fault,int[] r){StringBuilder sb=new StringBuilder();sb.Append("[DPS PRINT COMMAND]\nVersion=").Append(VERSION).Append("\nCommand=").Append(arg).Append("\nMode=").Append(mode).Append("\nBaysSet=").Append(set).Append("\nSkippedUnavailable=").Append(skip).Append("\nSkippedFault=").Append(fault).Append("\nProjectorsSeen=").Append(r[0]).Append("\nTurnedOn=").Append(r[1]).Append("\nTurnedOff=").Append(r[2]).Append("\nNote=PRINT owns projector/welder state. DPS keeps projector Keep Projection enabled, forces welder Help Others, and now allows longer no-progress windows before hard PRINT STALL. COMPLETE requires active projector RemainingBlocks=0; READY requires connector.\n\n[PRINT ACTIVE]\n");for(int i=1;i<=ActBays();i++)if(PrintSlot[i]>0)sb.Append("BAY").Append(B2(i)).Append("=PJ").Append(B2(PrintSlot[i])).Append("\n");sb.Append("\n[BAY STATES]\n");for(int i=1;i<=ActBays();i++){sb.Append("BAY").Append(B2(i)).Append("=").Append(LightStateName(BayState[i])).Append("\n  LOADED=PJ").Append(B2(LoadedSlot[i])).Append("\n  NEXT=PJ").Append(B2(Sel[i])).Append("\n");}SetReport(sb.ToString());}

void DoLaunch(string u,string arg){LoadCfg();int ab=ActBays(),set=0,skip=0;bool all=u.StartsWith("LAUNCH ALL");bool incComplete=Has(u,"COMPLETE");int bay=BayNum(u);if(!all&&bay<1){CommandReport("LAUNCH","Use LAUNCH BAY##, LAUNCH ALL, or LAUNCH ALL COMPLETE.");return;}int a=all?1:bay,z=all?ab:bay;for(int b=a;b<=z&&b<=MAXB;b++){int st=BayState[b];bool ok=st==LS_READY||(incComplete&&st==LS_COMPLETE)||(!all&&st==LS_COMPLETE);if(!ok){skip++;continue;}Bay y=LiveB!=null?LiveB[b]:null;if(y==null||!y.Core()){skip++;continue;}BayState[b]=LS_LAUNCH;BayStopped[b]=false;PrintSlot[b]=0;LaunchSec[b]=0;LaunchPhase[b]=0;OpenLaunchHardware(y);set++;}ResetFastLS();FeedbackOnce();Status="LAUNCH set "+set+" skip "+skip;CommandReport("LAUNCH","Launch state set "+set+" bay(s), skipped "+skip+". Doors open, bay connector released, close waits for accepted O clear or fallback timer.");SetRunFreq();}
void OpenLaunchHardware(Bay y){if(y==null)return;for(int i=0;i<y.Gates.Count;i++){IMyDoor d=y.Gates[i];if(d!=null)d.OpenDoor();}for(int i=0;i<y.Cs.Count;i++){IMyShipConnector c=y.Cs[i];if(c==null)continue;var a=c.GetActionWithName("Unlock");if(a!=null)a.Apply(c);IMyFunctionalBlock f=c as IMyFunctionalBlock;if(f!=null&&f.Enabled)f.Enabled=false;}for(int i=0;i<y.Ms.Count;i++){IMyFunctionalBlock f=y.Ms[i] as IMyFunctionalBlock;if(f!=null&&f.Enabled)f.Enabled=false;}}
void CheckLaunch(Bay y){if(y==null||y.N<1||BayState[y.N]!=LS_LAUNCH)return;int b=y.N;if(LaunchPhase[b]<=0){OpenLaunchHardware(y);LaunchSec[b]=0;LaunchPhase[b]=1;return;}if(LaunchPhase[b]==1){OpenLaunchHardware(y);if(!DoorsOpen(y)||!LaunchReleased(y))return;bool close=false;if(OccupancyCount(y)>0)close=OccupancyClear(y);else{LaunchSec[b]+=DtSec;close=LaunchSec[b]>=DoorCloseDelaySec;}if(close){for(int i=0;i<y.Gates.Count;i++){IMyDoor d=y.Gates[i];if(d!=null)d.CloseDoor();}LaunchPhase[b]=2;}return;}if(LaunchPhase[b]==2){if(DoorsClosed(y)){BayState[b]=LS_IDLE;ReadySlot[b]=0;LoadedSlot[b]=0;LaunchSec[b]=0;LaunchPhase[b]=0;FastLS[b]=-1;Status="BAY"+B2(b)+" LAUNCH CLEAR";PersistCfg();}}}
bool LaunchReleased(Bay y){if(y==null)return false;for(int i=0;i<y.Ms.Count;i++){IMyFunctionalBlock f=y.Ms[i] as IMyFunctionalBlock;if(f!=null&&f.Enabled)return false;}for(int i=0;i<y.Cs.Count;i++){IMyShipConnector c=y.Cs[i];if(c!=null&&c.Status.ToString()=="Connected")return false;}return true;}
bool DoorsOpen(Bay y){for(int i=0;i<y.Gates.Count;i++){IMyDoor d=y.Gates[i];if(d!=null&&d.Status.ToString()!="Open")return false;}return true;}
bool DoorsClosed(Bay y){for(int i=0;i<y.Gates.Count;i++){IMyDoor d=y.Gates[i];if(d!=null&&d.Status.ToString()!="Closed")return false;}return true;}
void ReconcileBayDoors(Bay y,int st){if(y==null||st==LS_LAUNCH)return;CloseBayDoors(y);}
void CloseBayDoors(Bay y){if(y==null)return;for(int i=0;i<y.Gates.Count;i++){IMyDoor d=y.Gates[i];if(d==null)continue;string s=d.Status.ToString();if(s!="Closed"&&s!="Closing")d.CloseDoor();}}
void CloseBayDoorsScan(int bay){int a=bay<1?1:bay,z=bay<1?ActBays():bay;Bay[] src=LiveB!=null?LiveB:B;for(int i=a;i<=z&&i<=MAXB;i++){Bay y=src[i];if(y!=null)CloseBayDoors(y);}}
int OccupancyCount(Bay y){return y==null?0:y.A;}
bool OccupancyClear(Bay y){if(OccupancyCount(y)<1)return false;return SensorsClear(y)&&CamerasClear(y);}
bool SensorsClear(Bay y){for(int i=0;i<y.Sens.Count;i++){IMySensorBlock sn=y.Sens[i];if(sn==null||sn.IsActive)return false;}return true;}
bool CamerasClear(Bay y){for(int i=0;i<y.As.Count;i++)if(CameraBlocked(y.As[i]))return false;return true;}
bool CameraBlocked(IMyCameraBlock c){if(c==null)return false;try{c.EnableRaycast=true;if(!c.CanScan(SENSOR_FRONT_SANITY_MAX_M))return false;var hit=c.Raycast(SENSOR_FRONT_SANITY_MAX_M);return !hit.IsEmpty();}catch{return false;}}
void ConfigLaunchSensorsAll(){for(int i=1;i<=MAXB;i++){Bay y=B[i];if(y==null||!y.Ready)continue;for(int n=0;n<y.Sens.Count;n++)ConfigLaunchSensor(y.Sens[n],y);}}
void ConfigLaunchSensor(IMySensorBlock s,Bay y){if(s==null||y==null||!y.Ready)return;IMyFunctionalBlock f=s as IMyFunctionalBlock;if(f!=null&&!f.Enabled)f.Enabled=true;s.DetectPlayers=false;s.DetectLargeShips=false;s.DetectSmallShips=true;s.DetectFloatingObjects=true;try{double gs=y.Grid!=null?y.Grid.GridSize:2.5;double span=Math.Abs(Axis(y.Max,y.OutAxis)-Axis(y.Min,y.OutAxis)+1)*gs;double len=Math.Max(SENSOR_FRONT_SANITY_MIN_M,Math.Min(SENSOR_FRONT_SANITY_MAX_M,span+SENSOR_FRONT_EXTRA_M));s.FrontExtend=(float)len;s.BackExtend=SENSOR_BACK_M;s.LeftExtend=SENSOR_SIDE_M;s.RightExtend=SENSOR_SIDE_M;s.TopExtend=SENSOR_TOP_M;s.BottomExtend=SENSOR_BOTTOM_M;}catch{}}
void PrepWelder(IMyShipWelder w){if(w==null)return;try{w.SetValueBool("HelpOthers",true);}catch{}}
void ApplyBayWelderState(Bay y,int st){if(y==null)return;bool want=st==LS_PRINT&&!BayStopped[y.N];for(int i=0;i<y.Wls.Count;i++){IMyShipWelder w=y.Wls[i];PrepWelder(w);IMyFunctionalBlock f=w as IMyFunctionalBlock;if(f!=null&&f.Enabled!=want)f.Enabled=want;}}
void ApplyPrintWeldersScan(int bay){List<IMyShipWelder> ws=new List<IMyShipWelder>();GridTerminalSystem.GetBlocksOfType<IMyShipWelder>(ws);for(int i=0;i<ws.Count;i++){IMyShipWelder w=ws[i];if(w==null||Ex(w)||Foreign(w.CustomName))continue;int b=BayNum(w.CustomName);if(b<1||b>MAXB)continue;if(bay>0&&b!=bay)continue;bool want=PrintSlot[b]>0&&!BayStopped[b];PrepWelder(w);IMyFunctionalBlock f=w as IMyFunctionalBlock;if(f!=null&&f.Enabled!=want)f.Enabled=want;}}
void StopHardwareScan(int bay){List<IMyProjector> ps=new List<IMyProjector>();GridTerminalSystem.GetBlocksOfType<IMyProjector>(ps);for(int i=0;i<ps.Count;i++){IMyProjector p=ps[i];if(!ValidPj(p))continue;KeepPj(p);int b=BayNum(p.CustomName);if(bay>0&&b!=bay)continue;IMyFunctionalBlock f=p as IMyFunctionalBlock;if(f!=null)f.Enabled=false;}List<IMyShipWelder> ws=new List<IMyShipWelder>();GridTerminalSystem.GetBlocksOfType<IMyShipWelder>(ws);for(int i=0;i<ws.Count;i++){IMyShipWelder w=ws[i];if(w==null||Ex(w)||Foreign(w.CustomName))continue;int b=BayNum(w.CustomName);if(bay>0&&b!=bay)continue;PrepWelder(w);IMyFunctionalBlock f=w as IMyFunctionalBlock;if(f!=null)f.Enabled=false;}}

void DoSelect(int bay,int slot,string arg){LoadCfg();int ab=ActBays();int changed=0,skip=0;if(bay>0){if(BaySlotAvailable(bay,slot)){Sel[bay]=slot;changed++;}else skip++;}else{for(int i=1;i<=ab;i++){if(BaySlotAvailable(i,slot)){Sel[i]=slot;changed++;}else skip++;}}int[] r=SelectPjAudit(bay,slot);SetSelectReport(arg,r[0],r[1],r[2]);Status="SELECT "+(bay>0?B2(bay):"ALL")+" PJ"+B2(slot)+" set "+changed+" unavail "+skip;LastState="SELECT";LastBays=ab;LastPJ=r[2];SetRunFreq();}
int[] SelectPjAudit(int bay,int slot){List<IMyProjector> ps=new List<IMyProjector>();GridTerminalSystem.GetBlocksOfType<IMyProjector>(ps);int seen=0,on=0,unavail=0;for(int i=0;i<ps.Count;i++){IMyProjector pj=ps[i];if(!ValidPj(pj))continue;int b=BayNum(pj.CustomName);if(bay>0&&b!=bay)continue;seen++;IMyFunctionalBlock f=pj as IMyFunctionalBlock;if(f!=null&&f.Enabled)on++;}int a=bay>0?bay:1,z=bay>0?bay:ActBays();for(int b=a;b<=z&&b<=MAXB;b++)if(!BaySlotAvailable(b,slot))unavail++;return new int[]{seen,on,unavail};}
bool BaySlotAvailable(int bay,int slot){if(bay<1||bay>MAXB||slot<1||slot>MAXS)return false;Bay y=LiveB!=null?LiveB[bay]:null;int mask=ExpectedSlotMask(y);return SlotBit(mask,slot);}

void StartRotorAlign(string arg){RotAlignRun=true;RotAlignTick=0;Paused=false;SetRunFreq();RotorAlignStep();RotorAlignReport(arg,"STARTED");Status="ROTOR ALIGN started";}
void RotorAlignStep(){if(!RotAlignRun)return;RotAlignTick++;List<IMyMotorStator> rs=new List<IMyMotorStator>();GridTerminalSystem.GetBlocksOfType<IMyMotorStator>(rs);RotAlignSeen=RotAlignLocked=RotAlignMoving=0;for(int i=0;i<rs.Count;i++){IMyMotorStator r=rs[i];if(!RotorMine(r))continue;RotAlignSeen++;PrepRotorZero(r);if(RotAlignTick>=ROTOR_ALIGN_TIMEOUT_TICKS){r.TargetVelocityRPM=0;TryLock(r,true);RotAlignLocked++;}else{double a=NormDeg(r.Angle*180.0/Math.PI);double d=AngDiff(ROTOR_TARGET_DEG,a);TryLock(r,false);r.TargetVelocityRPM=(float)(d>=0?ROTOR_RPM:-ROTOR_RPM);RotAlignMoving++;}}Upd("ROTOR_ALIGN");if(RotAlignSeen<1||RotAlignTick>=ROTOR_ALIGN_TIMEOUT_TICKS){RotAlignRun=false;for(int i=0;i<rs.Count;i++){IMyMotorStator r=rs[i];if(RotorMine(r)){PrepRotorZero(r);r.TargetVelocityRPM=0;TryLock(r,true);}}SetRunFreq();RotorAlignReport("ROTOR ALIGN","DONE");Status="ROTOR ALIGN done";}}
bool RotorMine(IMyMotorStator r){if(r==null||Ex(r))return false;string n=r.CustomName;int b=BayNum(n);return b>0&&b<=MAXB&&Has(n,Tag)&&Has(n,SYS);}
void PrepRotorZero(IMyMotorStator r){if(r==null)return;r.Enabled=true;r.LowerLimitDeg=(float)ROTOR_TARGET_DEG;r.UpperLimitDeg=(float)ROTOR_TARGET_DEG;}
void TryLock(IMyMotorStator r,bool on){if(r==null)return;var a=r.GetActionWithName(on?"Lock":"Unlock");if(a!=null)a.Apply(r);}
int LockDpsRotors(bool report){List<IMyMotorStator> rs=new List<IMyMotorStator>();GridTerminalSystem.GetBlocksOfType<IMyMotorStator>(rs);int n=0;for(int i=0;i<rs.Count;i++){IMyMotorStator r=rs[i];if(!RotorMine(r))continue;PrepRotorZero(r);r.TargetVelocityRPM=0;TryLock(r,true);n++;}if(report)CommandReport("ROTOR LOCK","Locked "+n+" DPS bay/support rotors.");return n;}
double NormDeg(double a){a=a%360.0;if(a<0)a+=360.0;return a;}
double AngDiff(double target,double current){double d=NormDeg(target)-NormDeg(current);while(d>180)d-=360;while(d<-180)d+=360;return d;}
void RotorAlignReport(string cmd,string phase){StringBuilder r=new StringBuilder();r.Append("[DPS ROTOR ALIGN]\nVersion=").Append(VERSION).Append("\nCommand=").Append(cmd).Append("\nPhase=").Append(phase).Append("\nRule=all DPS bay/support rotors target 0 deg; temporary helper, remove later.\nRPM=").Append(F(ROTOR_RPM)).Append("\nTargetDeg=").Append(F(ROTOR_TARGET_DEG)).Append("\nTick=").Append(RotAlignTick).Append("/" ).Append(ROTOR_ALIGN_TIMEOUT_TICKS).Append("\nSeen=").Append(RotAlignSeen).Append("\nMoving=").Append(RotAlignMoving).Append("\nLocked=").Append(RotAlignLocked).Append("\nNote=Rotors are forced ON, unlock while aligning, limits are set to 0/0 deg, then rotors stop and lock on timer. Normal AUTO also forces ON+0RPM+locked for DPS bay/support rotors.\nPerfLastRun=").Append(Hi).Append("/50000 ").Append(HiPhase).Append("\n");SetReport(r.ToString());}

void DoProjectorNames(string arg){LoadCfg();RefreshEntityAuthority();int[] r=CleanAllProjectorNames();StringBuilder sb=new StringBuilder();sb.Append("[DPS PROJECTOR NAME CLEANUP]\nVersion=").Append(VERSION).Append("\nCommand=").Append(arg).Append("\nProjectorsSeen=").Append(r[0]).Append("\nRenamed=").Append(r[1]).Append("\nSkipped=").Append(r[2]).Append("\nNote=Physical projector names stay lean. Role/Short remain in PROJECTOR SLOTS for UI/packets/commands.\n");SetReport(sb.ToString());Status="PROJECTOR NAMES renamed "+r[1];}
int[] CleanAllProjectorNames(){List<IMyProjector> ps=new List<IMyProjector>();GridTerminalSystem.GetBlocksOfType<IMyProjector>(ps);int seen=0,ren=0,skip=0;for(int i=0;i<ps.Count;i++){IMyProjector pj=ps[i];if(!ValidPj(pj)){skip++;continue;}int b=BayNum(pj.CustomName),sl=PjSlot(pj);if(b<1||sl<1){skip++;continue;}seen++;string nm=SlotPjName(b,sl);if(pj.CustomName!=nm&&RenameAllowed(pj)){pj.CustomName=nm;ren++;}}return new int[]{seen,ren,skip};}
void SetSelectReport(string arg,int seen,int on,int miss){StringBuilder r=new StringBuilder();r.Append("[DPS SELECT RESULT]\nVersion=").Append(VERSION).Append("\nCommand=").Append(arg).Append("\nProjectorsSeen=").Append(seen).Append("\nCurrentlyOn=").Append(on).Append("\nUnavailableSelected=").Append(miss).Append("\nPerfLastRun=").Append(Hi).Append("/50000 ").Append(HiPhase).Append("\nNote=SELECT chooses the future print slot only. Use SETUP/SHOW to turn projectors on for manual work.\n\n[BAY PROJECTOR SELECTIONS]\n");for(int i=1;i<=ActBays();i++)r.Append("BAY").Append(B2(i)).Append("=PJ").Append(B2(Sel[i])).Append("\n");SetReport(r.ToString());}
void DoSetup(int bay,int slot,string arg){SetupBay=bay;SetupSlot=slot;ShowSlot=0;int[] r=ApplyPjModeScan();ResetFastLS();FeedbackOnce();Status="SETUP "+B2(bay)+" PJ"+B2(slot);SetModeReport("SETUP",arg,r,"BAY"+B2(bay)+" PJ"+B2(slot)+" is on for manual blueprint setup. Lights use white setup state.");SetRunFreq();}
void DoShow(int slot,string arg){SetupBay=0;SetupSlot=0;ShowSlot=slot;int[] r=ApplyPjModeScan();ResetFastLS();FeedbackOnce();Status="SHOW PJ"+B2(slot);SetModeReport("SHOW",arg,r,"All PJ"+B2(slot)+" projectors are on for visual inspection/show-and-tell. Lights use white setup state.");SetRunFreq();}
void DoSetupOff(string arg){SetupBay=0;SetupSlot=0;ShowSlot=0;int[] r=ApplyPjModeScan();ResetFastLS();FeedbackOnce();Status="SETUP/SHOW OFF";SetModeReport("SETUP OFF",arg,r,"Setup/show mode cleared; projectors are off unless a future print mode requests them.");SetRunFreq();}
void DoSetupAccept(string u,string arg){LoadCfg();int b=BayNum(u),sl=SlotAfterBay(u);if(b<1)b=SetupBay;if(sl<1)sl=SetupSlot;if(b<1||sl<1){CommandReport("SETUP ACCEPT","No active setup bay/slot. Use SETUP BAY## PJ## first, or SETUP ACCEPT BAY## PJ##.");return;}int[] r=AcceptSetupFrom(b,sl);SetupBay=0;SetupSlot=0;ShowSlot=0;ApplyPjModeScan();ResetFastLS();FeedbackOnce();Status="SETUP ACCEPT "+B2(b)+" PJ"+B2(sl);StringBuilder sb=new StringBuilder();sb.Append("Master BAY").Append(B2(b)).Append(" PJ").Append(B2(sl)).Append(" accepted. Applied slot metadata and supported offset/rotation settings. Blueprint selection remains manual in Keen projector UI.");SetModeReport("SETUP ACCEPT",arg,r,sb.ToString());SetRunFreq();}
int[] AcceptSetupFrom(int bay,int slot){RefreshEntityAuthority();List<IMyProjector> ps=new List<IMyProjector>();GridTerminalSystem.GetBlocksOfType<IMyProjector>(ps);IMyProjector master=null;int seen=0,ren=0,copy=0,miss=0;for(int i=0;i<ps.Count;i++){IMyProjector pj=ps[i];if(!ValidPj(pj))continue;int b=BayNum(pj.CustomName),sl=PjSlot(pj);if(b==bay&&sl==slot){master=pj;break;}}if(master==null)return new int[]{0,0,0,1};Vector3I off=master.ProjectionOffset,rot=master.ProjectionRotation;for(int i=0;i<ps.Count;i++){IMyProjector pj=ps[i];if(!ValidPj(pj))continue;int b=BayNum(pj.CustomName),sl=PjSlot(pj);if(sl!=slot)continue;seen++;string nm=SlotPjName(b,slot);if(pj.CustomName!=nm&&RenameAllowed(pj)){pj.CustomName=nm;ren++;}KeepPj(pj);if(pj!=master){pj.ProjectionOffset=off;pj.ProjectionRotation=rot;pj.UpdateOffsetAndRotation();copy++;}}return new int[]{seen,ren,copy,miss};}
int[] ApplyPjModeScan(){List<IMyProjector> ps=new List<IMyProjector>();GridTerminalSystem.GetBlocksOfType<IMyProjector>(ps);int seen=0,on=0,off=0,miss=0;bool target=false;for(int i=0;i<ps.Count;i++){IMyProjector pj=ps[i];if(!ValidPj(pj))continue;int b=BayNum(pj.CustomName),sl=PjSlot(pj);bool want=WantPjOn(b,sl);seen++;if(want)target=true;KeepPj(pj);IMyFunctionalBlock f=pj as IMyFunctionalBlock;if(f!=null&&f.Enabled!=want){f.Enabled=want;if(want)on++;else off++;}}if((SetupBay>0||ShowSlot>0)&&!target)miss=1;return new int[]{seen,on,off,miss};}
bool ValidPj(IMyProjector pj){if(pj==null||Ex(pj)||Foreign(pj.CustomName))return false;int b=BayNum(pj.CustomName);if(b<1||b>MAXB)return false;return Has(pj.CustomName,Tag)||Has(pj.CustomName,SYS)||Has(pj.CustomName,"[BAY");}
bool WantPjOn(int bay,int slot){if(bay<1||bay>MAXB||BayStopped[bay])return false;if(PrintSlot[bay]>0)return slot==PrintSlot[bay];if(ShowSlot>0)return slot==ShowSlot;if(SetupBay>0)return bay==SetupBay&&slot==SetupSlot;return false;}
void ResetFastLS(){for(int i=0;i<=MAXB;i++)FastLS[i]=-1;}
void SetModeReport(string title,string arg,int[] r,string note){StringBuilder x=new StringBuilder();x.Append("[DPS PROJECTOR MODE]\nVersion=").Append(VERSION).Append("\nMode=").Append(title).Append("\nCommand=").Append(arg).Append("\nSetupBay=").Append(SetupBay>0?B2(SetupBay):"-").Append("\nSetupSlot=").Append(SetupSlot>0?"PJ"+B2(SetupSlot):"-").Append("\nShowSlot=").Append(ShowSlot>0?"PJ"+B2(ShowSlot):"-").Append("\nProjectorsSeen=").Append(r[0]).Append("\nTurnedOn=").Append(r[1]).Append("\nTurnedOff=").Append(r[2]).Append("\nMissingTarget=").Append(r[3]).Append("\nNote=").Append(note).Append("\n");SetReport(x.ToString());}
string SlotPjName(int bay,int slot){return Tag+" "+SYS+" [BAY"+B2(bay)+"] Projector PJ"+B2(slot);}
void AutoHeal(){for(int i=1;i<=MAXB;i++){Bay y=B[i];if(!y.Ready)continue;if(y.W<12)FindMany(y,"Welder",12-y.W);if(y.G<2)FindMany(y,"Gate",2-y.G);int mask=ExpectedSlotMask(y);if(MissingSlotCount(y,mask)>0)HealPjs(y,mask);if(y.M<1)FindMany(y,"Merge",1-y.M);if(y.C<1)FindMany(y,"Connector",1-y.C);if(y.A<1)FindMany(y,"O Sensor",1-y.A);}}
int MissingSlotCount(Bay y,int mask){int n=0;for(int s=1;s<=MAXS;s++)if(SlotBit(mask,s)&&!BayHasSlot(y,s))n++;return n;}
void HealPjs(Bay y,int mask){List<IMyProjector> cand=new List<IMyProjector>();for(int i=0;i<TP.Count;i++){IMyTerminalBlock x=TP[i];if(Cand(y,x,"Projector"))cand.Add(x as IMyProjector);}int miss=MissingSlotCount(y,mask);if(miss<1||cand.Count!=miss)return;SortPjVol(cand,y.Min,y.Max,false);int ci=0;for(int s=1;s<=MAXS&&ci<cand.Count;s++){if(SlotBit(mask,s)&&!BayHasSlot(y,s)){string nm=SlotPjName(y.N,s);if(cand[ci].CustomName!=nm)Q.Enqueue(new RenameJob(cand[ci],nm));ci++;}}}
int LongAx(Vector3D mn,Vector3D mx){Vector3D e=mx-mn;if(e.X>=e.Y&&e.X>=e.Z)return 0;if(e.Y>=e.Z)return 1;return 2;}
int OtherAx(int a,int b){for(int i=0;i<3;i++)if(i!=a&&i!=b)return i;return 0;}
double PjSpread(List<IMyProjector>a,int ax,bool world){double mn=0,mx=0;bool any=false;for(int i=0;i<a.Count;i++){IMyCubeBlock c=a[i] as IMyCubeBlock;if(c==null)continue;double v=Axis(world?c.GetPosition():LP(c),ax);if(!any){mn=mx=v;any=true;}else{mn=Math.Min(mn,v);mx=Math.Max(mx,v);}}return mx-mn;}
void SortPjVol(List<IMyProjector>a,Vector3D mn,Vector3D mx,bool world){if(a.Count<2)return;int la=LongAx(mn,mx),a1=(la==0?1:0),a2=OtherAx(la,a1);double s1=PjSpread(a,a1,world),s2=PjSpread(a,a2,world);int lat=s1>=s2?a1:a2,oth=OtherAx(la,lat);Vector3D ctr=(mn+mx)/2;double av=0;int n=0;for(int i=0;i<a.Count;i++){IMyCubeBlock c=a[i] as IMyCubeBlock;if(c==null)continue;av+=Axis(world?c.GetPosition():LP(c),la);n++;}int sg=(n>0&&av/n<Axis(ctr,la))?-1:1;for(int i=0;i<a.Count-1;i++)for(int j=i+1;j<a.Count;j++){double ui,uj,vi,vj;PjLineKey(a[i],lat,oth,ctr,sg,world,out ui,out vi);PjLineKey(a[j],lat,oth,ctr,sg,world,out uj,out vj);if(uj<ui-0.01||(Math.Abs(uj-ui)<=0.01&&vj<vi)){IMyProjector t=a[i];a[i]=a[j];a[j]=t;}}}
void PjLineKey(IMyProjector p,int lat,int oth,Vector3D ctr,int sg,bool world,out double u,out double v){IMyCubeBlock c=p as IMyCubeBlock;Vector3D q=c==null?ctr:(world?c.GetPosition():LP(c));u=(Axis(q,lat)-Axis(ctr,lat))*sg;v=Axis(q,oth)-Axis(ctr,oth);}
void FindMany(Bay y,string role,int need){if(need<=0)return;List<IMyTerminalBlock> src=CandList(role),f=new List<IMyTerminalBlock>();for(int i=0;i<src.Count;i++){IMyTerminalBlock x=src[i];if(!Cand(y,x,role))continue;f.Add(x);if(f.Count>need)return;}if(f.Count==0)return;bool[] used=new bool[32];MarkUsed(y,role,used);for(int i=0;i<f.Count;i++)Q.Enqueue(new RenameJob(f[i],Name(y.N,role,NextRoleNum(y,role,used))));}
List<IMyTerminalBlock> CandList(string r){if(r=="Welder")return TW;if(r=="Gate")return TD;if(r=="Projector")return TP;if(r=="Merge")return TM;if(r=="Connector")return TC;if(r=="O Camera")return TA;if(r=="O Sensor")return TN;return All;}
bool Cand(Bay y,IMyTerminalBlock x,string role){if(x==null||Ex(x)||Foreign(x.CustomName)||Has(x.CustomName,SYS))return false;if(!IsRole(x,role))return false;IMyCubeBlock c=x as IMyCubeBlock;if(c==null)return false;return RepairCandidate(y,c,role);}
void MarkUsed(Bay y,string role,bool[] used){if(role=="Projector"){for(int i=0;i<y.Pjs.Count;i++){int s=PjSlot(y.Pjs[i]);if(s>0&&s<used.Length)used[s]=true;}return;}List<IMyTerminalBlock> l=RoleList(y,role);for(int i=0;i<l.Count;i++){int n=RoleNo(l[i].CustomName);if(n>0&&n<used.Length)used[n]=true;}}
int NextRoleNum(Bay y,string role,bool[] used){for(int i=1;i<used.Length;i++)if(!used[i]){used[i]=true;return i;}return 1;}
List<IMyTerminalBlock> RoleList(Bay y,string role){List<IMyTerminalBlock> r=new List<IMyTerminalBlock>();if(role=="Welder"){for(int i=0;i<y.Wls.Count;i++)r.Add(y.Wls[i]);}else if(role=="Gate"){for(int i=0;i<y.Gates.Count;i++)r.Add(y.Gates[i]);}else if(role=="Projector"){for(int i=0;i<y.Pjs.Count;i++)r.Add(y.Pjs[i]);}else if(role=="Merge"){for(int i=0;i<y.Ms.Count;i++)r.Add(y.Ms[i]);}else if(role=="Connector"){for(int i=0;i<y.Cs.Count;i++)r.Add(y.Cs[i]);}else if(role=="O Camera"){for(int i=0;i<y.As.Count;i++)r.Add(y.As[i]);}else if(role=="O Sensor"){for(int i=0;i<y.Sens.Count;i++)r.Add(y.Sens[i]);}return r;}
int RoleNo(string n){if(n==null)return 0;int p=n.LastIndexOf(' ');if(p<0)return 0;return NumAt(n,p+1);}
bool RepairCandidate(Bay y,IMyCubeBlock c,string role){Vector3D p=LP(c);bool sg=c.CubeGrid==y.Grid;bool tc=false;if(role=="Gate")return sg&&InBox(y,p,0.05,false);if(role=="Projector")return RegDock(y,c,tc?32:18)||NearDock(y,c,tc?32:16.0)||(sg&&InBox(y,p,6.0,true));if(role=="O Camera"||role=="O Sensor")return DockRoleCandidate(y,c,p,sg,tc,tc?28:12,tc?28:3.0);if(role=="Merge"||role=="Connector")return DockRoleCandidate(y,c,p,sg,tc,tc?32:12,tc?32:4.0);return sg&&InBox(y,p,2.0,true);}
bool DockRoleCandidate(Bay y,IMyCubeBlock c,Vector3D p,bool sg,bool tc,double regPad,double nearPad){if(Reg[y.N])return RegDock(y,c,regPad)||NearDock(y,c,tc?regPad:nearPad);return NearDock(y,c,tc?regPad:nearPad)||(sg&&InBox(y,p,4.0,true));}
bool NearDock(Bay y,IMyCubeBlock c,double r){if(c==null)return false;Vector3D p=LP(c);bool any=false;double mnx=0,mny=0,mnz=0,mxx=0,mxy=0,mxz=0;AddDockBox(y,c,ref any,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);if(!any)return false;double pad=Math.Max(r,10);return p.X>=mnx-pad&&p.X<=mxx+pad&&p.Y>=mny-pad&&p.Y<=mxy+pad&&p.Z>=mnz-pad&&p.Z<=mxz+pad;}
void AddDockBox(Bay y,IMyCubeBlock c,ref bool any,ref double mnx,ref double mny,ref double mnz,ref double mxx,ref double mxy,ref double mxz){for(int i=0;i<y.Ms.Count;i++)BoxAdd(y.Ms[i] as IMyCubeBlock,c,ref any,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);for(int i=0;i<y.Cs.Count;i++)BoxAdd(y.Cs[i] as IMyCubeBlock,c,ref any,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);for(int i=0;i<y.Pjs.Count;i++)BoxAdd(y.Pjs[i] as IMyCubeBlock,c,ref any,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);for(int i=0;i<y.As.Count;i++)BoxAdd(y.As[i] as IMyCubeBlock,c,ref any,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);}
void BoxAdd(IMyCubeBlock a,IMyCubeBlock c,ref bool any,ref double mnx,ref double mny,ref double mnz,ref double mxx,ref double mxy,ref double mxz){if(a==null||a.CubeGrid!=c.CubeGrid)return;Vector3D q=LP(a);if(!any){mnx=mxx=q.X;mny=mxy=q.Y;mnz=mxz=q.Z;any=true;}else{if(q.X<mnx)mnx=q.X;if(q.X>mxx)mxx=q.X;if(q.Y<mny)mny=q.Y;if(q.Y>mxy)mxy=q.Y;if(q.Z<mnz)mnz=q.Z;if(q.Z>mxz)mxz=q.Z;}}
bool IsRole(IMyTerminalBlock x,string r){if(r=="Welder")return x is IMyShipWelder;if(r=="Gate")return x is IMyDoor;if(r=="Projector")return x is IMyProjector;if(r=="Merge")return x is IMyShipMergeBlock;if(r=="Connector")return x is IMyShipConnector;if(r=="O Camera")return x is IMyCameraBlock;if(r=="O Sensor")return x is IMySensorBlock;return false;}
int ApplyJobs(){int n=0;while(Q.Count>0&&n<APPLY_MAX&&Runtime.CurrentInstructionCount<22000){RenameJob j=Q.Dequeue();if(j.B!=null&&RenameAllowed(j.B)){j.B.CustomName=j.N;n++;}}Status="Renamed "+n+(Q.Count>0?" queued "+Q.Count:"");return n;}
void StartApply(string title,bool scanAfter){ApplyRun=true;ApplyScanAfter=scanAfter;ApplyTitle=title;ApplyTotal=Q.Count;ApplyDone=0;SetRunFreq();}
void ApplyStep(){ApplyDone+=ApplyJobs();if(Q.Count>0){Status=ApplyTitle+" "+ApplyDone+"/"+ApplyTotal;return;}ApplyRun=false;UpdateSlotMasksFromB();AutoOn=DiscPrevAuto;Paused=false;ReviewPause=false;if(DiscLights)PvAccept="\n[LIGHTS ACCEPT RESULT]\nAPPLIED RenameJobs="+ApplyDone+" Skipped"+LSkip+"\nAccept was staged to stay under instruction cap. Full status scan queued.\n";else PvAccept="\n[ACCEPT RESULT]\nAPPLIED RenameJobs="+ApplyDone+" CoreSAFE"+D_safe+" SupportSAFE"+D_sSafe+" O"+D_occ+"\nLights=SEPARATE\nAccept was staged to stay under instruction cap. Full status scan queued.\n";WriteDiscoveryReport();Status=ApplyTitle+" complete "+ApplyDone;if(ApplyScanAfter)BeginScanReport(false,true);else SetRunFreq();}


void LoadRegLine(string cd,int b){string k="D"+(b<10?"0":"")+b+"=";string v=Val(cd,k);if(v.Length==0)return;string[] p=v.Split(',');if(p.Length<7)return;long g;double a,b1,c,d,e,f;if(long.TryParse(p[0],out g)&&double.TryParse(p[1],out a)&&double.TryParse(p[2],out b1)&&double.TryParse(p[3],out c)&&double.TryParse(p[4],out d)&&double.TryParse(p[5],out e)&&double.TryParse(p[6],out f)){Reg[b]=true;RegGrid[b]=g;RegMin[b]=new Vector3D(a,b1,c);RegMax[b]=new Vector3D(d,e,f);}}
void AddRegText(StringBuilder s){s.Append("\n[DPS_REG]\n");for(int i=1;i<=MAXB;i++)if(Reg[i])s.Append("D").Append(i<10?"0":"").Append(i).Append("=").Append(RegGrid[i]).Append(',').Append(F(RegMin[i].X)).Append(',').Append(F(RegMin[i].Y)).Append(',').Append(F(RegMin[i].Z)).Append(',').Append(F(RegMax[i].X)).Append(',').Append(F(RegMax[i].Y)).Append(',').Append(F(RegMax[i].Z)).Append("\n");s.Append("\n");}
void LoadSlotRegLine(string cd,int b){string k="BAY"+(b<10?"0":"")+b+".Slots=";string v=Val(cd,k);if(v.Length==0)return;SlotMask[b]=SlotMaskFromText(v);}
int SlotMaskFromText(string v){int m=0;string u=v.ToUpper();string[] p=u.Split(',');for(int i=0;i<p.Length;i++){int s=SlotFrom(p[i].Trim());if(s>0&&s<=MAXS)m|=1<<(s-1);}return m;}
void AddSlotRegText(StringBuilder s){s.Append("\n[DPS_SLOT_REG]\n");for(int i=1;i<=MAXB;i++){int m=SlotMask[i];if(m==0&&LiveB!=null)m=SlotMaskFromBay(LiveB[i]);if(m==0)continue;s.Append("BAY").Append(B2(i)).Append(".Slots=").Append(SlotMaskText(m)).Append("\n");}s.Append("\n");}
string SlotMaskText(int m){StringBuilder z=new StringBuilder();bool first=true;for(int i=1;i<=MAXS;i++)if(SlotBit(m,i)){if(!first)z.Append(',');z.Append("PJ").Append(B2(i));first=false;}return z.ToString();}
void UpdateSlotMasksFromB(){for(int i=1;i<=MAXB;i++){int m=SlotMaskFromBay(B[i]);if(m!=0)SlotMask[i]=m;}}
string F(double d){return d.ToString("0.##");}
void UpdateReg(){for(int i=1;i<=MAXB;i++){Bay y=B[i];if(!y.Core())continue;if(Reg[i])continue;SetRegFrom(y);}}
void SetRegFrom(Bay y){bool any=false;long g=0;double mnx=0,mny=0,mnz=0,mxx=0,mxy=0,mxz=0;AddRoleBox(y.Ms,ref any,ref g,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);AddRoleBox(y.Cs,ref any,ref g,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);AddRoleBox(y.Pjs,ref any,ref g,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);AddRoleBox(y.As,ref any,ref g,ref mnx,ref mny,ref mnz,ref mxx,ref mxy,ref mxz);if(any){Reg[y.N]=true;RegGrid[y.N]=g;RegMin[y.N]=new Vector3D(mnx,mny,mnz);RegMax[y.N]=new Vector3D(mxx,mxy,mxz);}}
void AddRoleBox<T>(List<T> l,ref bool any,ref long g,ref double mnx,ref double mny,ref double mnz,ref double mxx,ref double mxy,ref double mxz) where T:IMyCubeBlock{for(int i=0;i<l.Count;i++){IMyCubeBlock b=l[i] as IMyCubeBlock;if(b==null)continue;if(!any){g=b.CubeGrid.EntityId;Vector3D q=LP(b);mnx=mxx=q.X;mny=mxy=q.Y;mnz=mxz=q.Z;any=true;}else if(b.CubeGrid.EntityId==g){Vector3D q=LP(b);if(q.X<mnx)mnx=q.X;if(q.X>mxx)mxx=q.X;if(q.Y<mny)mny=q.Y;if(q.Y>mxy)mxy=q.Y;if(q.Z<mnz)mnz=q.Z;if(q.Z>mxz)mxz=q.Z;}}}
bool RegDock(Bay y,IMyCubeBlock c,double pad){int n=y.N;if(!Reg[n]||c==null||c.CubeGrid.EntityId!=RegGrid[n])return false;Vector3D p=LP(c),mn=RegMin[n],mx=RegMax[n];return p.X>=mn.X-pad&&p.X<=mx.X+pad&&p.Y>=mn.Y-pad&&p.Y<=mx.Y+pad&&p.Z>=mn.Z-pad&&p.Z<=mx.Z+pad;}



void BeginDiscover(bool commission,bool accept,bool lights){ReviewPause=false;DiscPrevPaused=Paused;DiscPrevAuto=AutoOn;Paused=true;B=BuildB;DiscRun=true;DiscCommission=commission;DiscAccept=accept;DiscLights=lights;DiscStage=0;DiscIdx=0;DiscHi=0;DiscHiPhase="";SetRunFreq();DiscoverStep();}
void DiscoverStep(){if(DiscStage==0){LoadCfg();Clear();All.Clear();Lights.Clear();Panels.Clear();HelmLcds.Clear();DcsPb=null;TW.Clear();TD.Clear();TP.Clear();TM.Clear();TC.Clear();TA.Clear();TN.Clear();TS.Clear();GridTerminalSystem.GetBlocksOfType<IMyTerminalBlock>(All);EntityAuth=DetectEntityAuthorityFromAll();DiscIdx=0;DiscStage=1;Status="DISC typed";DUpd("DISC ALL");if(Runtime.CurrentInstructionCount>22000)return;}if(DiscStage==1){while(DiscIdx<All.Count&&Runtime.CurrentInstructionCount<22000){IMyTerminalBlock x=All[DiscIdx++];if(x==null||Ex(x))continue;if(DiscLights){IMyLightingBlock lb0=x as IMyLightingBlock;if(lb0!=null)Lights.Add(lb0);}if(!DiscOk(x))continue;if(x is IMyShipWelder)TW.Add(x);else if(x is IMyDoor)TD.Add(x);else if(x is IMyProjector)TP.Add(x);else if(x is IMyShipMergeBlock)TM.Add(x);else if(x is IMyShipConnector)TC.Add(x);else if(x is IMyCameraBlock)TA.Add(x);else if(x is IMySensorBlock)TN.Add(x);else if(x is IMyMotorStator)TS.Add(x);int b=BayNum(x.CustomName);if(b>0&&b<=MAXB&&(Has(x.CustomName,SYS)||Has(x.CustomName,"[BAY"))&&(Has(x.CustomName,Tag)||!LeadTag(x.CustomName)))RoleScan(x,b);}DUpd("DISC TYPED");if(DiscIdx<All.Count)return;DiscStage=2;}if(DiscStage==2){BuildBounds();D_ep=Math.Max(1,ConfigSlotCount());D_wg=TW.Count/12;D_wr=TW.Count%12;D_pg=D_best>0?0:TP.Count/D_ep;D_pr=TP.Count%D_ep;D_bs=D_bm=D_bc=D_bp=D_bo=0;for(int i=1;i<=MAXB;i++){Bay y=B[i];if(!y.Core())continue;D_bs++;if(y.M>0)D_bm++;if(y.C>0)D_bc++;if(y.P>0)D_bp++;if(y.A>0)D_bo++;}DUpd("DISC COUNT");DiscStage=3;return;}if(DiscStage==3){D_rv=D_rm=D_rc=D_rp=D_ro=0;InferReachCore(D_ep,ref D_rv,ref D_rm,ref D_rc,ref D_rp,ref D_ro);DUpd("DISC INFER");DiscStage=4;return;}if(DiscStage==4){BuildSupportPlan();DUpd("DISC SUPPORT");DiscStage=5;return;}if(DiscStage==5&&DiscLights){LightStart();DUpd("DISC LIGHT INIT");DiscStage=6;return;}if(DiscStage==6&&DiscLights){LightStep();DUpd("DISC LIGHTS");if(LIdx<Lights.Count)return;LightReport();DiscStage=7;}if(DiscStage==5||DiscStage==7){int mw=D_wr==0?D_wg:0;D_best=BestGuess(mw,D_bm,D_bp,D_bc);D_agree=Agree(D_best,mw,D_bm,D_bp,D_bc);D_conf=D_agree>=3?"HIGH":(D_agree>=2?"MED":"LOW");if(DiscAccept){if(DiscLights)TryAcceptLights();else TryAcceptCommission();}WriteDiscoveryReport();DiscRun=false;if(AccRun){SetRunFreq();return;}if(ApplyRun){SetRunFreq();Status="Accept applying "+Q.Count+" jobs";return;}AutoOn=DiscPrevAuto;Paused=DiscPrevPaused;if(DiscAccept){SetRunFreq();BeginScanReport(false,true);}else {B=LiveB;if(DiscCommission){ReviewPause=true;if(AutoOn)Paused=true;Status="DRYRUN complete - review Custom Data, run AUTO";}else Status="Discovery "+D_conf+" "+D_best;SetRunFreq();}}}
void WriteDiscoveryReport(){StringBuilder r=new StringBuilder();r.Append((DiscLights?(DiscAccept?"[DPS LIGHTS ACCEPT]\n":"[DPS LIGHTS DRYRUN]\n"):(DiscAccept?"[DPS COMMISSION ACCEPT]\n":(DiscCommission?"[DPS BAY COMMISSION DRYRUN]\n":"[DPS DISCOVERY]\n")))).Append("Version=").Append(VERSION).Append("\nMode=").Append((DiscLights?(DiscAccept?"COMMISSION LIGHTS ACCEPT":"COMMISSION LIGHTS DRYRUN"):(DiscAccept?"COMMISSION ACCEPT":(DiscCommission?"BAY COMMISSION DRYRUN":"STAGED DRYRUN")))).Append("\nTag=").Append(Tag).Append("\nBayGuess=").Append(D_best).Append("\nConfidence=").Append(D_conf).Append("\nAgree=").Append(D_agree).Append("\nPerfStageMax=").Append(DiscHi).Append("/50000 ").Append(DiscHiPhase).Append("\nPerfLastRun=").Append(Hi).Append("/50000 ").Append(HiPhase).Append("\nPerfLifetime=").Append(HiCap).Append("/50000 ").Append(HiCapPhase).Append("\n\n[ANCHORS RAW]\nWelders=").Append(TW.Count).Append(" W12Groups=").Append(D_wg).Append(" Rem=").Append(D_wr).Append("\nProjectors=").Append(TP.Count).Append(" SlotDefs=").Append(D_ep).Append(" PGroups=").Append(D_pg).Append(" Rem=").Append(D_pr).Append("\nMerges=").Append(TM.Count).Append(" Connectors=").Append(TC.Count).Append(" Cameras=").Append(TA.Count).Append(" SupportCandidates=").Append(TS.Count).Append(" Lights=").Append(Lights.Count).Append("\n\n[ANCHORS BAY-AWARE]\nTaggedBays=").Append(D_bs).Append(" M").Append(D_bm).Append(" C").Append(D_bc).Append(" P").Append(D_bp).Append(" O").Append(D_bo).Append("\nExtraMerges=").Append(Math.Max(0,TM.Count-D_bm)).Append(" ExtraConnectors=").Append(Math.Max(0,TC.Count-D_bc)).Append("\n\n[ANCHORS INFERRED-PRINT]\nPrintVolumes=").Append(D_rv).Append(" M").Append(D_rm).Append(" C").Append(D_rc).Append(" P").Append(D_rp).Append(" O").Append(D_ro).Append(PvAnchor).Append(PvNum).Append(PvPlan).Append(PvSupport).Append(PvFoot).Append(PvLight).Append(PvAccept).Append("\n[NOTES]\nStaged scan/accept. DRYRUN previews; ACCEPT applies; STATUS refreshes current state.\n");SetReport(r.ToString());LastState=DiscAccept?(DiscLights?"LIGHTS ACCEPT":"ACCEPT"):"DISCOVER";LastBays=D_best;if(DiscLights){LastLI=0;LastLX=0;for(int i=1;i<=MAXB;i++){LastLI+=LLI[i];LastLX+=LLX[i];}}}
void InferReachCore(int ep,ref int rv,ref int rm,ref int rc,ref int rp,ref int ro){PvAnchor="";PvNum="";PvPlan="";DClus.Clear();for(int i=0;i<TW.Count;i++){IMyCubeBlock b=TW[i] as IMyCubeBlock;if(b!=null)AddRCl(b);}SortDCl();StringBuilder h=new StringBuilder();h.Append("\n[PRINT VOLUME DOCK ANCHORS]\n");for(int i=0;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;rv++;int[] a=AnchorVals(d.W,ep);if(a[0]>0)rm++;if(a[1]>0)rc++;if(a[2]>0)rp++;if(a[3]>0)ro++;h.Append(rv<10?"0":"").Append(rv).Append(" anchor=").Append((a[0]>0&&a[1]>0)?"MC":(a[0]>0?"M":(a[1]>0?"C":"NONE"))).Append(" conf=").Append((a[0]>0&&a[1]>0&&a[2]>0&&a[3]>0)?"HIGH":((a[0]+a[1]>0&&a[2]>0)?"MED":"LOW")).Append(" M").Append(a[0]).Append(" C").Append(a[1]).Append(" P").Append(a[2]).Append(" O").Append(a[3]).Append(" D").Append(a[4]).Append("\n");}BuildNumbering();PvAnchor=h.ToString();}
int[] AnchorVals(Vector3D pv,int ep){IMyCubeBlock m;double md=BestBlock(TM,pv,out m);IMyCubeBlock c;double cd=BestBlock(TC,pv,out c);IMyCubeGrid g=null;if(m!=null&&c!=null)g=md<=cd?m.CubeGrid:c.CubeGrid;else if(m!=null)g=m.CubeGrid;else if(c!=null)g=c.CubeGrid;int[] a=new int[5];if(g!=null){a[0]=SameGridCount(TM,g);a[1]=SameGridCount(TC,g);a[2]=SameGridCount(TP,g);a[3]=SameGridCount(TA,g)+SameGridCount(TN,g);a[4]=(int)(g.EntityId%1000000000);}return a;}
void BuildNumbering(){StringBuilder s=new StringBuilder();s.Append("\n[NUMBERING]\nPolicy=").Append(BayNumbering).Append(" RefTag=").Append(RefTag).Append("\n");RefBlock=FindRef();if(RefBlock==null){s.Append("Reference=AMBIGUOUS_OR_MISSING AutoNumbering=OFF\n");PvNum=s.ToString();return;}s.Append("Reference=").Append(SN(RefBlock.CustomName)).Append("\nAutoNumbering=DRYRUN\n");if(BayNumbering!="SEQUENTIAL"&&BayNumbering!="SERPENTINE"){s.Append("UnsupportedPolicy=1\n");PvNum=s.ToString();return;}if(BayNumbering=="SEQUENTIAL")SortPolicySeq();else SortPolicySerp();for(int i=0,b=1;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;s.Append("BAY").Append(b<10?"0":"").Append(b).Append(" <- curr=").Append(CurBayForPV(d.W)).Append(" @").Append(F(d.W.X)).Append(',').Append(F(d.W.Y)).Append(',').Append(F(d.W.Z)).Append("\n");b++;}PvNum=s.ToString();BuildPlan();}
void BuildSupportPlan(){PvSupport="";D_sSafe=0;D_sCheck=0;StringBuilder s=new StringBuilder();s.Append("\n[SUPPORT COMMISSION DRYRUN]\n");for(int i=0,b=1;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;IMyCubeGrid ag=AnchorGrid(d.W);bool need=ag!=null&&ag!=d.G;IMyCubeBlock sup;double sd=BestBlock(TS,d.W,out sup);bool ok=need&&sup!=null&&sd<225;if(!need){s.Append("BAY").Append(b<10?"0":"").Append(b).Append(" S0 SKIP same-grid/no-bridge-needed\n");}else if(ok){D_sSafe++;s.Append("BAY").Append(b<10?"0":"").Append(b).Append(" S1 SAFE ").Append(SN(((IMyTerminalBlock)sup).CustomName)).Append(" d=").Append(F(Math.Sqrt(sd))).Append("\n");}else{D_sCheck++;s.Append("BAY").Append(b<10?"0":"").Append(b).Append(" S? CHECK bridge-needed no-unique-visible-support\n");}b++;}s.Append("Summary SupportSAFE").Append(D_sSafe).Append(" SupportCHECK").Append(D_sCheck).Append("\nNote: only terminal support blocks can be renamed/tracked; rotor heads/converters may not be terminal-visible.\n");PvSupport=s.ToString();}
void BuildPlan(){StringBuilder s=new StringBuilder();s.Append(DiscCommission?"\n[BAY COMMISSION DRYRUN]\n":"\n[COMMISSION PLAN]\n");D_safe=D_remap=D_check=D_ren=D_occ=0;for(int i=0,b=1;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;int[] a=AnchorVals(d.W,D_ep);int o=a[3];D_occ+=o;string cur=CurBayForPV(d.W),tar=(b<10?"0":"")+b;bool safe=d.N==12&&a[0]==1&&a[1]==1&&a[2]>0&&o>=1;bool conflict=cur!="-"&&cur!="?"&&cur!=tar;bool match=cur==tar;string st=safe&&!conflict?"SAFE":(safe?"REMAP":"CHECK");if(st=="SAFE")D_safe++;else if(st=="REMAP")D_remap++;else D_check++;if(!match)D_ren+=d.N+a[0]+a[1]+a[2]+o;s.Append("BAY").Append(tar).Append(' ').Append(st).Append(" curr=").Append(cur).Append(" W").Append(d.N).Append(" M").Append(a[0]).Append(" C").Append(a[1]).Append(" P").Append(a[2]).Append(" O").Append(o);if(DiscCommission)s.Append(" rename~").Append(match?0:d.N+a[0]+a[1]+a[2]+o);s.Append("\n");b++;}if(DiscCommission)s.Append("Summary SAFE").Append(D_safe).Append(" REMAP").Append(D_remap).Append(" CHECK").Append(D_check).Append(" O").Append(D_occ).Append(" RenameApprox").Append(D_ren).Append("\nNo names changed by DRYRUN. ACCEPT applies core/support/O detectors; bay lighting remains separate.\n");PvPlan=s.ToString();}
void BuildActionableCells(){for(int i=0;i<DClus.Count;i++)DClus[i].AC.Clear();for(int i=0;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;for(int j=0;j<TW.Count;j++){IMyCubeBlock wb=TW[j] as IMyCubeBlock;if(wb==null)continue;Vector3D p=wb.GetPosition()+wb.WorldMatrix.Forward*2.5;if(Vector3D.DistanceSquared(p,d.W)>16)continue;AddFaceAdjCells(wb,d.AC);}}}
void BuildAdjacentWeldAudit(){StringBuilder s=new StringBuilder();s.Append("\n[ACTIONABLE WELD AREA CHECK]\nRule=union of cells adjacent to each welder working-face footprint\n");for(int i=0,b=1;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;s.Append(AdjLine(d,b++));}s.Append("Note: world light positions are transformed to grid-local cell coordinates before LI distance.\n");PvFoot=s.ToString();}
string AdjLine(DCl d,int bay){Vector3I mn,mx;CellBounds(d.AC,out mn,out mx);int sx=d.AC.Count<1?0:mx.X-mn.X+1,sy=d.AC.Count<1?0:mx.Y-mn.Y+1,sz=d.AC.Count<1?0:mx.Z-mn.Z+1;return "BAY"+(bay<10?"0":"")+bay+" W"+d.N+" AdjCells="+d.AC.Count+" span="+sx+","+sy+","+sz+" sorted="+Sort3(sx,sy,sz)+"\n";}
void AddFaceAdjCells(IMyCubeBlock b,List<Vector3I> cells){Vector3D lf=Vector3D.TransformNormal(b.WorldMatrix.Forward,MatrixD.Transpose(b.CubeGrid.WorldMatrix));int ax=0,sg=lf.X>=0?1:-1;double av=Math.Abs(lf.X);if(Math.Abs(lf.Y)>av){ax=1;av=Math.Abs(lf.Y);sg=lf.Y>=0?1:-1;}if(Math.Abs(lf.Z)>av){ax=2;sg=lf.Z>=0?1:-1;}Vector3I mn=b.Min,mx=b.Max;int x0=mn.X,x1=mx.X,y0=mn.Y,y1=mx.Y,z0=mn.Z,z1=mx.Z;if(ax==0){int x=sg>0?mx.X+1:mn.X-1;for(int y=y0;y<=y1;y++)for(int z=z0;z<=z1;z++)AddCell(cells,new Vector3I(x,y,z));}else if(ax==1){int y=sg>0?mx.Y+1:mn.Y-1;for(int x=x0;x<=x1;x++)for(int z=z0;z<=z1;z++)AddCell(cells,new Vector3I(x,y,z));}else{int z=sg>0?mx.Z+1:mn.Z-1;for(int x=x0;x<=x1;x++)for(int y=y0;y<=y1;y++)AddCell(cells,new Vector3I(x,y,z));}}
void AddCell(List<Vector3I> l,Vector3I c){if(!HasCell(l,c))l.Add(c);}
bool HasCell(List<Vector3I> l,Vector3I c){for(int i=0;i<l.Count;i++)if(l[i]==c)return true;return false;}
void CellBounds(List<Vector3I> l,out Vector3I mn,out Vector3I mx){mn=new Vector3I(0,0,0);mx=new Vector3I(0,0,0);if(l.Count<1)return;mn=mx=l[0];for(int i=1;i<l.Count;i++){Vector3I c=l[i];mn=new Vector3I(Math.Min(mn.X,c.X),Math.Min(mn.Y,c.Y),Math.Min(mn.Z,c.Z));mx=new Vector3I(Math.Max(mx.X,c.X),Math.Max(mx.Y,c.Y),Math.Max(mx.Z,c.Z));}}
string Sort3(int a,int b,int c){if(a>b){int t=a;a=b;b=t;}if(b>c){int t=b;b=c;c=t;}if(a>b){int t=a;a=b;b=t;}return a+"x"+b+"x"+c;}
void LightStart(){BuildActionableCells();BuildAdjacentWeldAudit();PvLight="";LSkip=LASeen=0;LIdx=0;for(int i=0;i<=MAXB;i++){LLI[i]=0;LLX[i]=0;}}
void LightStep(){while(LIdx<Lights.Count&&Runtime.CurrentInstructionCount<22000){IMyTerminalBlock tb=Lights[LIdx++];IMyCubeBlock b=tb as IMyCubeBlock;LASeen++;bool bad=b==null||Ex(tb)||Foreign(tb.CustomName);if(bad){LSkip++;continue;}int bay=LightLX(b);if(bay>0){LLX[bay]++;if(DiscAccept)QR(tb,LightName(bay,"LX",LLX[bay]));}else{bay=LightLI(b);if(bay>0){LLI[bay]++;if(DiscAccept)QR(tb,LightName(bay,"LI",LLI[bay]));}else LSkip++;}}}
void LightReport(){StringBuilder s=new StringBuilder();s.Append("\n[LIGHTS ").Append(DiscAccept?"ACCEPT PLAN":"DRYRUN").Append("]\n");s.Append("Settings LIExtra=").Append(F(LiExtra)).Append(" LXGate=").Append(F(LxGate)).Append("\n");int tli=0,tlx=0;for(int i=1;i<=MAXB;i++){if(!B[i].Core())continue;tli+=LLI[i];tlx+=LLX[i];s.Append("BAY").Append(i<10?"0":"").Append(i).Append(" LI").Append(LLI[i]).Append(" LX").Append(LLX[i]).Append("\n");}s.Append("Totals LI").Append(tli).Append(" LX").Append(tlx).Append(" Skipped").Append(LSkip).Append(" Seen").Append(LASeen).Append("\n");if(DiscAccept)s.Append("Names queued for accepted LI/LX lights.\n");else s.Append("No names changed. Disposable per-light trace removed after ARGOS/DPS bay-light cause was proven.\n");PvLight=s.ToString();}
string B2(int b){return b<1?"--":((b<10?"0":"")+b);}
void NearLV(Vector3D p,out int bay,out double dist){bay=0;dist=1e9;for(int i=0,b=1;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;double dd=DistActionable(d,p);if(dd<dist){dist=dd;bay=b;}b++;}}
double DistActionable(DCl d,Vector3D p){if(d.AC.Count<1||d.G==null)return 1e9;MatrixD inv=MatrixD.Invert(d.G.WorldMatrix);Vector3D lp=Vector3D.Transform(p,inv);double gs=Math.Max(0.1,d.G.GridSize);lp=new Vector3D(lp.X/gs,lp.Y/gs,lp.Z/gs);double e=LiExtra/gs,best=1e9;for(int i=0;i<d.AC.Count;i++){Vector3I c=d.AC[i];double dd=DistCell(lp,c,e);if(dd<best)best=dd;}return best*gs;}
double DistCell(Vector3D p,Vector3I c,double e){double mnx=c.X-0.5-e,mny=c.Y-0.5-e,mnz=c.Z-0.5-e,mxx=c.X+0.5+e,mxy=c.Y+0.5+e,mxz=c.Z+0.5+e;if(mnx>mxx||mny>mxy||mnz>mxz)return 1e9;double dx=p.X<mnx?mnx-p.X:(p.X>mxx?p.X-mxx:0),dy=p.Y<mny?mny-p.Y:(p.Y>mxy?p.Y-mxy:0),dz=p.Z<mnz?mnz-p.Z:(p.Z>mxz?p.Z-mxz:0);return Math.Sqrt(dx*dx+dy*dy+dz*dz);}
int DockBay(IMyCubeBlock lb){int hit=0;for(int i=0,b=1;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;IMyCubeGrid ag=AnchorGrid(d.W);if(ag!=null&&ag!=d.G&&lb.CubeGrid==ag){if(hit>0)return-1;hit=b;}b++;}return hit;}
void NearGate(Vector3D p,out int bay,out double dist,out double side){bay=0;dist=1e9;side=0;for(int i=0,b=1;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16){continue;}for(int g=0;g<B[b].Gates.Count;g++){IMyCubeBlock gate=B[b].Gates[g] as IMyCubeBlock;if(gate==null)continue;Vector3D gp=gate.GetPosition();double dd=Vector3D.Distance(p,gp);if(dd<dist){dist=dd;bay=b;side=Vector3D.Dot(p-gp,gp-d.W);}}b++;}}
int LightLI(IMyCubeBlock lb){int dk=DockBay(lb);if(dk>0)return dk;Vector3D p=lb.GetPosition();int bay;double dist;NearLV(p,out bay,out dist);return bay>0&&dist<=0?bay:0;}
int LightLX(IMyCubeBlock lb){Vector3D p=lb.GetPosition();int bay;double dist,side;NearGate(p,out bay,out dist,out side);return bay>0&&dist<=LxGate&&side>0?bay:0;}
string LightName(int bay,string role,int n){return Tag+" "+SYS+" [BAY"+(bay<10?"0":"")+bay+"] "+role+" "+(n<10?"0":"")+n;}
string LcdName(int bay,int n){return Tag+" "+SYS+" [BAY"+B2(bay)+"] LCD "+B2(n);}
bool IsHelmLcd(IMyTextPanel p){if(p==null||Ex(p)||Foreign(p.CustomName))return false;string n=p.CustomName.ToUpper();if(!Has(n,SYS)||Has(n,"[BAY"))return false;if(Has(n,"[DCS]"))return false;return Has(n,Tag)||EntityAuth;}
void TryAcceptLights(){int li=0,lx=0;for(int i=1;i<=MAXB;i++){li+=LLI[i];lx+=LLX[i];}if(li+lx<1){PvAccept="\n[LIGHTS ACCEPT RESULT]\nREFUSED No owned/classified lights found.\n";return;}int jobs=Q.Count;PvAccept="\n[LIGHTS ACCEPT RESULT]\nAPPLYING RenameJobs="+jobs+" LI"+li+" LX"+lx+" Skipped"+LSkip+"\nStaged rename/adoption is running to stay under instruction cap.\n";StartApply("LIGHTS ACCEPT",true);}
void TryAcceptCommission(){PvAccept="";if(D_best<1||D_safe!=D_best||D_remap>0||D_check>0||D_sCheck>0){PvAccept="\n[ACCEPT RESULT]\nREFUSED CoreSAFE"+D_safe+" REMAP"+D_remap+" CHECK"+D_check+" SupportCHECK"+D_sCheck+"\n";return;}AccRun=true;AccIdx=0;AccBay=1;AccJobs=0;PvAccept="\n[ACCEPT RESULT]\nQUEUEING CoreSAFE"+D_safe+" SupportSAFE"+D_sSafe+" O"+D_occ+"\nAccept queue is staged by bay before rename apply to stay under instruction cap.\n";Status="COMMISSION ACCEPT queueing";}
void AcceptQueueStep(){while(AccIdx<DClus.Count&&Runtime.CurrentInstructionCount<14000){DCl d=DClus[AccIdx++];if(d.N<8||d.N>16)continue;if(AccBay>D_best){AccIdx=DClus.Count;break;}int b=AccBay++;string p=Tag+" "+SYS+" [BAY"+B2(b)+"] ";int j=0;j+=QueueWelders(d,p);IMyCubeGrid g=AnchorGrid(d.W);if(g!=null){j+=QueueGrid(TM,g,p+"Merge ");j+=QueueGrid(TC,g,p+"Connector ");j+=QueueProjectorsGrid(TP,g,b,d);j+=QueueGrid(TA,g,p+"O Camera ");j+=QueueSensorsForBay(b,p+"O Sensor ");}IMyCubeBlock sup;double sd=BestBlock(TS,d.W,out sup);if(sup!=null&&sd<225)j+=QR((IMyTerminalBlock)sup,p+"Rotor 01");AccJobs+=j;Status="COMMISSION ACCEPT queue BAY"+B2(b)+" jobs "+AccJobs;return;}if(AccIdx<DClus.Count)return;AccRun=false;PvAccept="\n[ACCEPT RESULT]\nAPPLYING RenameJobs="+AccJobs+" CoreSAFE"+D_safe+" SupportSAFE"+D_sSafe+" O"+D_occ+"\nQueue build and rename apply are both staged to stay under instruction cap.\n";StartApply("COMMISSION ACCEPT",true);WriteDiscoveryReport();Status="COMMISSION ACCEPT apply "+Q.Count+" jobs";}
int QueueSensorsForBay(int bay,string p){int n=0;List<IMySensorBlock>a=new List<IMySensorBlock>();for(int i=0;i<TN.Count;i++){IMySensorBlock sn=TN[i] as IMySensorBlock;IMyCubeBlock cb=sn as IMyCubeBlock;if(sn==null||cb==null)continue;double d;if(SensorBay(cb,out d)==bay)a.Add(sn);}SortSensors(a);for(int i=0;i<a.Count;i++)n+=QR(a[i],p+(i+1<10?"0":"")+(i+1));return n;}
int SensorBay(IMyCubeBlock cb,out double dist){dist=1e30;if(cb==null)return 0;Vector3D p=cb.GetPosition();int hit=0,bay=1;double second=1e30;for(int i=0;i<DClus.Count;i++){DCl d=DClus[i];if(d.N<8||d.N>16)continue;IMyCubeGrid ag=AnchorGrid(d.W);bool gridok=(ag!=null&&cb.CubeGrid==ag)||cb.CubeGrid==d.G;if(gridok){double dd=Vector3D.Distance(p,d.W);if(dd<dist){second=dist;dist=dd;hit=bay;}else if(dd<second)second=dd;}bay++;}if(hit>0&&dist<=SENSOR_COMMISSION_MAX_M&&(second-dist>=SENSOR_COMMISSION_GAP_M||second>1e20))return hit;return 0;}
void SortSensors(List<IMySensorBlock>a){for(int i=0;i<a.Count-1;i++)for(int j=i+1;j<a.Count;j++)if(SN(a[j].CustomName).CompareTo(SN(a[i].CustomName))<0){IMySensorBlock t=a[i];a[i]=a[j];a[j]=t;}}
int QueueWelders(DCl d,string p){int n=0;for(int i=0;i<TW.Count;i++){IMyCubeBlock b=TW[i] as IMyCubeBlock;if(b==null)continue;Vector3D w=b.GetPosition()+b.WorldMatrix.Forward*2.5;if(Vector3D.DistanceSquared(w,d.W)<16)n+=QR(TW[i],p+"Welder "+(++n<10?"0":"")+n);}return n;}
int QueueGrid(List<IMyTerminalBlock> l,IMyCubeGrid g,string p){int n=0;for(int i=0;i<l.Count;i++){IMyCubeBlock b=l[i] as IMyCubeBlock;if(b!=null&&b.CubeGrid==g)n+=QR(l[i],p+(n+1<10?"0":"")+(n+1));}return n;}
int QueueProjectorsGrid(List<IMyTerminalBlock> l,IMyCubeGrid g,int bay,DCl d){List<IMyProjector>a=new List<IMyProjector>();for(int i=0;i<l.Count;i++){IMyProjector pj=l[i] as IMyProjector;IMyCubeBlock b=pj as IMyCubeBlock;if(pj!=null&&b!=null&&b.CubeGrid==g)a.Add(pj);}SortPjVol(a,d.Mn,d.Mx,true);int n=0;for(int i=0;i<a.Count&&i<MAXS;i++)n+=QR(a[i],SlotPjName(bay,i+1));return n;}
int QR(IMyTerminalBlock b,string n){if(!RenameAllowed(b))return 0;if(b.CustomName==n)return 0;Q.Enqueue(new RenameJob(b,n));return 1;}
IMyTerminalBlock FindRef(){int n;bool amb;IMyTerminalBlock x=PickRef(RefTag,true,false,out n,out amb);if(n>0)return amb?null:x;x=PickRef(Tag,true,true,out n,out amb);if(n>0)return amb?null:x;x=PickRef("",false,true,out n,out amb);return n>0?(amb?null:x):null;}
IMyTerminalBlock PickRef(string tag,bool useTag,bool onlyCtrl,out int n,out bool amb){IMyTerminalBlock one=null;n=0;amb=false;for(int i=0;i<All.Count;i++){IMyTerminalBlock x=All[i];if(x==null)continue;if(onlyCtrl&&!(x is IMyShipController))continue;if(useTag&&!Has(x.CustomName,tag))continue;if(one==null)one=x;else if(!SameRef(one,x))amb=true;n++;}return one;}
bool SameRef(IMyTerminalBlock a,IMyTerminalBlock b){return Math.Abs(Vector3D.Dot(a.WorldMatrix.Forward,b.WorldMatrix.Forward))>0.98&&Math.Abs(Vector3D.Dot(a.WorldMatrix.Up,b.WorldMatrix.Up))>0.98;}
void SortPolicySeq(){if(RefBlock==null)return;Vector3D f=RefBlock.WorldMatrix.Forward,r=RefBlock.WorldMatrix.Right;for(int i=0;i<DClus.Count-1;i++)for(int j=i+1;j<DClus.Count;j++){double fi=Vector3D.Dot(DClus[i].W,f),fj=Vector3D.Dot(DClus[j].W,f),ri=Vector3D.Dot(DClus[i].W,r),rj=Vector3D.Dot(DClus[j].W,r);bool sw=fj>fi+0.5||(Math.Abs(fj-fi)<=0.5&&rj<ri);if(sw){DCl t=DClus[i];DClus[i]=DClus[j];DClus[j]=t;}}}
void SortPolicySerp(){if(RefBlock==null)return;Vector3D f=RefBlock.WorldMatrix.Forward,r=RefBlock.WorldMatrix.Right;for(int i=0;i<DClus.Count-1;i++)for(int j=i+1;j<DClus.Count;j++){double ai=Math.Atan2(Vector3D.Dot(DClus[i].W,r),Vector3D.Dot(DClus[i].W,f)),aj=Math.Atan2(Vector3D.Dot(DClus[j].W,r),Vector3D.Dot(DClus[j].W,f));if(ai<0)ai+=Math.PI*2;if(aj<0)aj+=Math.PI*2;if(aj<ai){DCl t=DClus[i];DClus[i]=DClus[j];DClus[j]=t;}}}
string CurBayForPV(Vector3D pv){IMyCubeGrid g=AnchorGrid(pv);if(g==null)return"-";for(int i=1;i<=MAXB;i++)if(Reg[i]&&RegGrid[i]==g.EntityId)return (i<10?"0":"")+i;return"?";}
IMyCubeGrid AnchorGrid(Vector3D pv){IMyCubeBlock m;double md=BestBlock(TM,pv,out m);IMyCubeBlock c;double cd=BestBlock(TC,pv,out c);if(m!=null&&c!=null)return md<=cd?m.CubeGrid:c.CubeGrid;if(m!=null)return m.CubeGrid;if(c!=null)return c.CubeGrid;return null;}
double BestBlock(List<IMyTerminalBlock> l,Vector3D pv,out IMyCubeBlock best){best=null;double bd=1e30;for(int i=0;i<l.Count;i++){IMyCubeBlock b=l[i] as IMyCubeBlock;if(b==null)continue;double d=Vector3D.DistanceSquared(b.GetPosition(),pv);if(d<bd){bd=d;best=b;}}return bd;}
void AddRCl(IMyCubeBlock b){Vector3D w=b.GetPosition()+b.WorldMatrix.Forward*2.5;double br=16;DCl best=null;for(int i=0;i<DClus.Count;i++){DCl d=DClus[i];double ds=Vector3D.DistanceSquared(w,d.W);if(ds<br){br=ds;best=d;}}if(best==null){best=new DCl();best.G=b.CubeGrid;best.W=w;best.Mn=w;best.Mx=w;best.N=1;DClus.Add(best);}else{best.N++;double n=best.N;best.W=(best.W*(n-1)+w)/n;best.Mn=new Vector3D(Math.Min(best.Mn.X,w.X),Math.Min(best.Mn.Y,w.Y),Math.Min(best.Mn.Z,w.Z));best.Mx=new Vector3D(Math.Max(best.Mx.X,w.X),Math.Max(best.Mx.Y,w.Y),Math.Max(best.Mx.Z,w.Z));}}
void SortDCl(){for(int i=0;i<DClus.Count-1;i++)for(int j=i+1;j<DClus.Count;j++){Vector3D a=DClus[i].W,b=DClus[j].W;bool sw=false;if(a.X>b.X+0.1)sw=true;else if(Math.Abs(a.X-b.X)<=0.1&&a.Z>b.Z+0.1)sw=true;else if(Math.Abs(a.X-b.X)<=0.1&&Math.Abs(a.Z-b.Z)<=0.1&&a.Y>b.Y)sw=true;if(sw){DCl t=DClus[i];DClus[i]=DClus[j];DClus[j]=t;}}}
int SameGridCount(List<IMyTerminalBlock> l,IMyCubeGrid g){int n=0;for(int i=0;i<l.Count;i++){IMyCubeBlock b=l[i] as IMyCubeBlock;if(b!=null&&b.CubeGrid==g)n++;}return n;}
bool DiscOk(IMyTerminalBlock x){if(x==null||Ex(x)||Foreign(x.CustomName))return false;if(Has(x.CustomName,Tag)||!LeadTag(x.CustomName))return true;return false;}
bool LeadTag(string n){return n!=null&&n.Length>1&&n[0]=='['&&n.IndexOf(']')>0;}
int BestGuess(int a,int b,int c,int d){int best=0,bc=0;int[] v=new int[]{a,b,c,d};for(int i=0;i<v.Length;i++){if(v[i]<1)continue;int n=0;for(int j=0;j<v.Length;j++)if(v[j]==v[i])n++;if(n>bc){bc=n;best=v[i];}}return best;}
int Agree(int best,int a,int b,int c,int d){if(best<1)return 0;int n=0;if(a==best)n++;if(b==best)n++;if(c==best)n++;if(d==best)n++;return n;}
string SN(string s){if(s==null)return"";s=s.Replace("\n"," ");return s.Length>40?s.Substring(0,40):s;}
void LoadCfg(){string cd=Me.CustomData;string t=Val(cd,"Tag=");if(t.Length>0)Tag=t.Trim();string ae=Val(cd,"Enabled=");if(ae.Length>0)AutoOn=ae.ToUpper()!="FALSE";int mb=IVal(cd,"ManagedBays=",ManagedBays);ManagedBays=mb<1?1:(mb>MAXB?MAXB:mb);string eh=Val(cd,"ExpectedBayHardware=");if(eh.Length>0)ExpectedHardware=eh.Trim();int r=IVal(cd,"RefreshSeconds=",RefreshSec);RefreshSec=r<1?10:r;double dd;string dcs=Val(cd,"DoorCloseDelaySeconds=");if(double.TryParse(dcs,out dd))DoorCloseDelaySec=dd<1?10:dd;string bn=Val(cd,"BayNumbering=");if(bn.Length>0)BayNumbering=bn.Trim().ToUpper();string rt=Val(cd,"ReferenceTag=");if(rt.Length>0)RefTag=rt.Trim();double dv;string li=Val(cd,"InteriorLightExtraMeters=");if(double.TryParse(li,out dv))LiExtra=dv;string lx=Val(cd,"ExteriorLightGateMeters=");if(double.TryParse(lx,out dv))LxGate=Math.Max(0,dv);LoadSlots(cd);for(int i=1;i<=MAXB;i++){int v=IVal(cd,"BAY"+(i<10?"0":"")+i+"=PJ",0);if(v<1)v=IVal(cd,(i<10?"0":"")+i+"=PJ",Sel[i]);if(v>0)Sel[i]=v;LoadRegLine(cd,i);LoadSlotRegLine(cd,i);LoadBayStateLine(cd,i);}}
void LoadSlots(string cd){for(int i=1;i<=MAXS;i++){string k="PJ"+(i<10?"0":"")+i;string r=Val(cd,k+".Role="),l=Val(cd,k+".Label="),sh=Val(cd,k+".Short=");if(r.Length>0){SR[i]=r.Trim().ToUpper();SL[i]=SR[i];}if(l.Length>0&&r.Length==0)SL[i]=l.Trim().ToUpper();if(sh.Length>0)SS[i]=sh.Trim().ToUpper();string c=Val(cd,k+"=");if(c.Length>0){string[] p=c.Split(',');if(p.Length>0&&p[0].Trim().Length>0){SR[i]=p[0].Trim().ToUpper();SL[i]=SR[i];}if(p.Length>1&&p[1].Trim().Length>0)SS[i]=p[1].Trim().ToUpper();}}}
void LoadBayStateLine(string cd,int i){string k="BAY"+(i<10?"0":"")+i+".State=";string v=Val(cd,k);if(v.Length<1)v=Val(cd,"BAY"+(i<10?"0":"")+i+"State=");int st=StateVal(v);BayState[i]=st;BayStopped[i]=st==LS_STOPPED;int ld=SlotFrom(Val(cd,"BAY"+(i<10?"0":"")+i+".Loaded="));if(ld<1)ld=SlotFrom(Val(cd,"BAY"+(i<10?"0":"")+i+"Loaded="));if(ld>0)LoadedSlot[i]=ld;else if(st==LS_READY||st==LS_COMPLETE)LoadedSlot[i]=Sel[i];PrintSlot[i]=st==LS_PRINT?(LoadedSlot[i]>0?LoadedSlot[i]:Sel[i]):0;ReadySlot[i]=st==LS_READY?LoadedSlot[i]:0;LastRemain[i]=-1;StallTicks[i]=0;}
int StateVal(string v){v=(v==null?"":v.Trim().ToUpper());if(v=="FAULT")return LS_FAULT;if(v=="PRINT"||v=="PRINTING")return LS_PRINT;if(v=="COMPLETE")return LS_COMPLETE;if(v=="READY")return LS_READY;if(v=="LAUNCH"||v=="LAUNCHING")return LS_LAUNCH;if(v=="STOPPED"||v=="STOP")return LS_STOPPED;if(v=="EMPTY"||v=="IDLE")return LS_IDLE;return LS_IDLE;}
int ActBays(){int n=ManagedBays;if(LastBays>n)n=LastBays;if(D_best>n)n=D_best;return n<1?1:(n>MAXB?MAXB:n);}
string CfgText(){StringBuilder s=new StringBuilder();int ab=ActBays();s.Append("[ENTITY]\nTag=").Append(Tag).Append("\nSystem=DPS\n\n[DPS_MANAGER]\nManagedBays=").Append(ab).Append("\nExpectedBayHardware=").Append(ExpectedHardware).Append("\n\n[AUTO]\nEnabled=").Append(AutoOn?"true":"false").Append("\nRefreshSeconds=").Append(RefreshSec).Append("\n\n[DPS_DISCOVERY]\nBayNumbering=").Append(BayNumbering).Append("\nReferenceTag=").Append(RefTag).Append("\n\n[DPS_LIGHTS]\nInteriorLightExtraMeters=").Append(F(LiExtra)).Append("\nExteriorLightGateMeters=").Append(F(LxGate)).Append("\n\n[DPS_LAUNCH]\nDoorCloseDelaySeconds=").Append(F(DoorCloseDelaySec)).Append("\n\n[PROJECTOR SLOTS]\n");for(int i=1;i<=MAXS;i++)if(SR[i]!="")s.Append("PJ").Append(B2(i)).Append(".Role=").Append(SR[i]).Append("\nPJ").Append(B2(i)).Append(".Short=").Append(SS[i]).Append("\n");s.Append("\n[BAY NEXT]\n");for(int i=1;i<=ab;i++)s.Append("BAY").Append(B2(i)).Append("=PJ").Append(B2(Sel[i])).Append("\n");s.Append("\n[BAY LOADED]\n");for(int i=1;i<=ab;i++)if(LoadedSlot[i]>0)s.Append("BAY").Append(B2(i)).Append(".Loaded=PJ").Append(B2(LoadedSlot[i])).Append("\n");s.Append("\n[DPS_BAY_STATE]\n");for(int i=1;i<=ab;i++)s.Append("BAY").Append(B2(i)).Append(".State=").Append(LightStateName(BayState[i])).Append("\n");s.Append("\n# <DPS_COMMANDS_BEGIN>\n[DPS MANAGER COMMANDS]\nCOMMISSION DRYRUN|ACCEPT\nCOMMISSION LIGHTS DRYRUN|ACCEPT\nSTATUS; AUTO|AUTO OFF\nSHOW PJ##|SHOW OFF\nSETUP BAY## PJ##|SETUP ACCEPT|SETUP OFF\nSELECT BAY## PJ##|SELECT ALL INT\nPRINT BAY## PJ##|PRINT ALL PJ##\nLAUNCH BAY##|ALL|ALL COMPLETE\nSTOP/CLEAR BAY##|ALL\nPROJECTOR NAMES; ROTOR ALIGN\nExclude: [NODPS]\n# <DPS_COMMANDS_END>\n");AddRegText(s);AddSlotRegText(s);return s.ToString();}
string KeepReport(){string cd=Me.CustomData;int i=cd.IndexOf("# <DPS_LAST_REPORT_BEGIN>");return i>=0?"\n"+cd.Substring(i):"";}
void PersistCfg(){Me.CustomData=CfgText()+KeepReport();}


void CheckDcsServiceEvents(){if(DcsPb==null){PbTmp.Clear();GridTerminalSystem.GetBlocksOfType<IMyProgrammableBlock>(PbTmp);for(int i=0;i<PbTmp.Count;i++){IMyProgrammableBlock p=PbTmp[i];if(p!=null&&p!=Me&&Has(p.CustomName,Tag)&&Has(p.CustomName,"[DCS]")&&!Ex(p)){DcsPb=p;break;}}}if(DcsPb==null)return;string cd=DcsPb.CustomData;if(cd==null||cd.IndexOf(DCS_SVC_BEGIN)<0)return;bool ch=false;int ab=ActBays();for(int i=1;i<=ab;i++){int q=IVal(cd,"BAY"+B2(i)+".ServiceLockedSeq=",0);if(q<1||q==DcsSvcSeen[i])continue;Bay y=LiveB[i];if(y==null||!y.Core())continue;SetRegFrom(y);DcsSvcSeen[i]=q;DcsRegRefresh="BAY"+B2(i)+" seq "+q;ch=true;}if(ch)PersistCfg();}
void FeedbackLane(){if(Paused||!AutoOn||DiscRun||LiveB==null)return;CheckDcsServiceEvents();int ab=ActBays();for(int i=1;i<=ab;i++){Bay y=LiveB[i];if(y==null||!y.Core())continue;ServiceBayReadyHardware(y);CheckPrintCompletion(y);CheckLaunch(y);int st=FastBayLightState(y);ApplyBayLightState(y,st);UpdateBayLcds(y,st);ReconcileBayDoors(y,st);ApplyBayWelderState(y,st);}UpdateHelmLcds();Upd("FEEDBACK_LIGHTS");}
void FeedbackOnce(){if(LiveB==null)return;int ab=ActBays();for(int i=1;i<=ab;i++){Bay y=LiveB[i];if(y==null||!y.Core())continue;ServiceBayReadyHardware(y);CheckPrintCompletion(y);CheckLaunch(y);int st=FastBayLightState(y);ApplyBayLightState(y,st);UpdateBayLcds(y,st);ReconcileBayDoors(y,st);ApplyBayWelderState(y,st);}UpdateHelmLcds();Upd("FEEDBACK_ONCE");}
void CompletePrint(Bay y,int b,int sl){PrintSlot[b]=0;LoadedSlot[b]=sl;BayState[b]=LS_COMPLETE;SetSlotProjectorOn(y,sl,false);ApplyBayWelderState(y,LS_COMPLETE);ServiceBayReadyHardware(y);FastLS[b]=-1;Status="BAY"+B2(b)+" COMPLETE PJ"+B2(sl);PersistCfg();}
void PrintFault(Bay y,string code,IMyProjector pj){int b=y.N;BayState[b]=LS_FAULT;ApplyBayWelderState(y,LS_FAULT);FastLS[b]=-1;Status="BAY"+B2(b)+" "+code;SetPrintDiagReport(y,code,pj);PersistCfg();}
void SetPrintDiagReport(Bay y,string code,IMyProjector pj){int b=y.N,sl=PrintSlot[b];StringBuilder r=new StringBuilder();r.Append("[DPS PRINT DIAG]\nVersion=").Append(VERSION).Append("\nBay=BAY").Append(B2(b)).Append("\nSlot=PJ").Append(B2(sl)).Append("\nFault=").Append(code).Append("\nLastRemain=").Append(LastRemain[b]).Append("\nStallTicks=").Append(StallTicks[b]).Append("/").Append(PRINT_STALL_TICKS).Append("\nPjWaitTicks=").Append(PRINT_PJ_WAIT_TICKS).Append("\n");if(pj==null)r.Append("Projector=NULL\n");else r.Append("Projector=").Append(pj.CustomName).Append("\nIsProjecting=").Append(pj.IsProjecting?"YES":"NO").Append("\nTotalBlocks=").Append(pj.TotalBlocks).Append("\nRemainingBlocks=").Append(pj.RemainingBlocks).Append("\nBuildableBlocks=").Append(pj.BuildableBlocksCount).Append("\n");r.Append("Note=V178 keeps welders/projector on during longer temporary no-progress windows. Hard fault means no progress persisted through the full stall window or projection never became/lost valid.\n");SetReport(r.ToString());}
void CheckPrintCompletion(Bay y){if(y==null||y.N<1||BayStopped[y.N])return;int b=y.N,sl=PrintSlot[b];if(sl>0&&BayState[b]==LS_PRINT){IMyProjector pj=SlotProjector(y,sl);if(pj==null)return;bool act=pj.IsProjecting&&pj.TotalBlocks>0;if(!act){if(LastRemain[b]>=0){StallTicks[b]++;if(StallTicks[b]>=PRINT_PJ_WAIT_TICKS){PrintFault(y,"PJ LOST PROJECTION",pj);}}else if(LastRemain[b]>-PRINT_PJ_WAIT_TICKS)LastRemain[b]--;else{PrintFault(y,"PJ NOT PROJECTING",pj);}return;}int rem=pj.RemainingBlocks;if(rem<=0){CompletePrint(y,b,sl);return;}if(LastRemain[b]>=0&&rem>=LastRemain[b])StallTicks[b]++;else StallTicks[b]=0;LastRemain[b]=rem;if(StallTicks[b]>=PRINT_STALL_TICKS){PrintFault(y,"PRINT STALL",pj);return;}}if(BayState[b]==LS_COMPLETE&&BayConnectorConnected(y)){int ls=LoadedSlot[b]>0?LoadedSlot[b]:Sel[b];ReadySlot[b]=ls;BayState[b]=LS_READY;FastLS[b]=-1;Status="BAY"+B2(b)+" READY PJ"+B2(ls);PersistCfg();}}
IMyProjector SlotProjector(Bay y,int sl){if(y==null)return null;for(int i=0;i<y.Pjs.Count;i++){IMyProjector p=y.Pjs[i];if(p!=null&&PjSlot(p)==sl)return p;}return null;}
void SetSlotProjectorOn(Bay y,int sl,bool on){IMyProjector p=SlotProjector(y,sl);KeepPj(p);IMyFunctionalBlock f=p as IMyFunctionalBlock;if(f!=null&&f.Enabled!=on)f.Enabled=on;}
void KeepPj(IMyProjector p){if(p==null)return;try{p.SetValueBool("KeepProjection",true);}catch{}}
void ServiceBayReadyHardware(Bay y){if(y==null||y.N<1)return;int stt=BayState[y.N];if(stt==LS_LAUNCH||stt==LS_STOPPED)return;bool mergePrep=(stt==LS_IDLE||stt==LS_PRINT||stt==LS_SETUP);if(mergePrep){for(int i=0;i<y.Ms.Count;i++){IMyFunctionalBlock f=y.Ms[i] as IMyFunctionalBlock;if(f!=null&&!f.Enabled)f.Enabled=true;}}for(int i=0;i<y.Cs.Count;i++){IMyShipConnector c=y.Cs[i];IMyFunctionalBlock f=c as IMyFunctionalBlock;if(f!=null&&!f.Enabled)f.Enabled=true;if(c!=null){string st=c.Status.ToString();if(st=="Connectable"||st=="ReadyToConnect"){var a=c.GetActionWithName("Lock");if(a!=null)a.Apply(c);}}}}
bool BayConnectorConnected(Bay y){if(y==null)return false;for(int i=0;i<y.Cs.Count;i++){IMyShipConnector c=y.Cs[i];if(c!=null&&c.Status.ToString()=="Connected")return true;}return false;}
int FastBayLightState(Bay y){if(y==null||!y.Core())return LS_IDLE;if(BayStopped[y.N])return LS_STOPPED;if(BayState[y.N]==LS_FAULT)return LS_FAULT;if(y.Miss>0||y.PCtl>0||FastBayFault(y))return LS_FAULT;if(BayInSetup(y))return LS_SETUP;if(BayState[y.N]==LS_PRINT)return LS_PRINT;if(BayState[y.N]==LS_COMPLETE)return LS_COMPLETE;if(BayState[y.N]==LS_READY)return LS_READY;if(BayState[y.N]==LS_LAUNCH)return LS_LAUNCH;return LS_IDLE;}
bool FastBayFault(Bay y){for(int i=0;i<y.Wls.Count;i++)if(BadFast(y.Wls[i]))return true;for(int i=0;i<y.Gates.Count;i++)if(BadFast(y.Gates[i]))return true;for(int i=0;i<y.Pjs.Count;i++)if(BadFast(y.Pjs[i]))return true;for(int i=0;i<y.Ms.Count;i++)if(BadFast(y.Ms[i]))return true;for(int i=0;i<y.Cs.Count;i++)if(BadFast(y.Cs[i]))return true;for(int i=0;i<y.As.Count;i++)if(BadFast(y.As[i]))return true;for(int i=0;i<y.Sens.Count;i++)if(BadFast(y.Sens[i]))return true;return false;}
bool BadFast(IMyTerminalBlock b){IMyCubeBlock c=b as IMyCubeBlock;return c==null||!c.IsFunctional;}

int BayLightState(Bay y){if(y==null||!y.Core())return LS_IDLE;if(BayStopped[y.N])return LS_STOPPED;if(BayState[y.N]==LS_FAULT)return LS_FAULT;if(y.Miss>0||y.Dmg>0||y.PCtl>0)return LS_FAULT;if(BayInSetup(y))return LS_SETUP;if(BayState[y.N]==LS_PRINT)return LS_PRINT;if(BayState[y.N]==LS_COMPLETE)return LS_COMPLETE;if(BayState[y.N]==LS_READY)return LS_READY;if(BayState[y.N]==LS_LAUNCH)return LS_LAUNCH;return LS_IDLE;}
bool BayInSetup(Bay y){if(y==null||BayStopped[y.N])return false;if(SetupBay>0)return y.N==SetupBay;if(ShowSlot>0)return BayHasSlot(y,ShowSlot);return false;}
bool BayHasSlot(Bay y,int slot){for(int i=0;i<y.Pjs.Count;i++)if(PjSlot(y.Pjs[i])==slot)return true;return false;}
string LightStateName(int st){if(st==LS_FAULT)return"FAULT";if(st==LS_PRINT)return"PRINTING";if(st==LS_COMPLETE)return"COMPLETE";if(st==LS_READY)return"READY";if(st==LS_LAUNCH)return"LAUNCHING";if(st==LS_SETUP)return"SETUP";if(st==LS_STOPPED)return"STOPPED";return"EMPTY";}
void ApplyBayLightState(Bay y,int st){if(y==null)return;if(FastLS[y.N]==st)return;for(int k=0;k<y.Lts.Count;k++){IMyLightingBlock l=y.Lts[k];if(l==null)continue;string n=l.CustomName.ToUpper();bool lx=Has(n,"LX")||Has(n,"EXTERIOR")||Has(n,"LG");if(lx)ApplyLX(l,st);else ApplyLI(l,st);}FastLS[y.N]=st;}
void ApplyLI(IMyLightingBlock l,int st){if(st==LS_FAULT||st==LS_STOPPED)SetLight(l,true,new Color(255,191,0));else if(st==LS_PRINT)SetLight(l,true,Color.Red);else if(st==LS_COMPLETE||st==LS_SETUP)SetLight(l,true,Color.White);else if(st==LS_READY)SetLight(l,true,Color.Green);else if(st==LS_LAUNCH)SetLight(l,true,Color.Blue);else SetLight(l,false,Color.White);}
void ApplyLX(IMyLightingBlock l,int st){if(st==LS_LAUNCH)SetLight(l,true,Color.Blue);else SetLight(l,false,Color.White);}
void SetLight(IMyLightingBlock l,bool on,Color c){if(l==null)return;l.Color=c;l.Enabled=on;}
Color StateColor(int st){if(st==LS_FAULT||st==LS_STOPPED)return new Color(255,191,0);if(st==LS_PRINT)return Color.Red;if(st==LS_COMPLETE||st==LS_SETUP)return Color.White;if(st==LS_READY)return Color.Green;if(st==LS_LAUNCH)return Color.Blue;return Color.White;}
void UpdateBayLcds(Bay y,int st){if(y==null||y.Lcds.Count==0)return;int ls=LoadedSlot[y.N],nx=Sel[y.N];string msg=LightStateName(st)+"\nBAY "+B2(y.N)+"\n"+(ls>0?"LOADED "+Clip(SlotShort(ls),8)+"\n":"")+"NEXT "+Clip(SlotShort(nx),8)+"\n";Color c=StateColor(st);for(int i=0;i<y.Lcds.Count;i++){IMyTextPanel p=y.Lcds[i];if(p==null)continue;try{p.ContentType=ContentType.TEXT_AND_IMAGE;p.Alignment=TextAlignment.CENTER;p.FontSize=2.35f;p.FontColor=c;p.WriteText(msg,false);}catch{}}}

void UpdateHelmLcds(){if(HelmLcds.Count==0||LiveB==null)return;string msg=BuildHelmText();Color c=HelmColor();for(int i=0;i<HelmLcds.Count;i++){IMyTextPanel p=HelmLcds[i];if(p==null||Ex(p))continue;try{p.ContentType=ContentType.TEXT_AND_IMAGE;p.Alignment=TextAlignment.LEFT;p.FontSize=1.15f;p.FontColor=c;p.WriteText(msg,false);}catch{}}}
Color HelmColor(){if(LiveB==null)return Color.White;int ab=ActBays();bool rd=false,co=false;for(int i=1;i<=ab;i++){Bay y=LiveB[i];int st=BayLightState(y);if(st==LS_FAULT||st==LS_STOPPED)return new Color(255,191,0);if(st==LS_LAUNCH)return Color.Blue;if(st==LS_PRINT)return Color.Red;if(st==LS_COMPLETE)co=true;else if(st==LS_READY)rd=true;}if(co)return Color.White;if(rd)return Color.Green;return Color.White;}
string BuildHelmText(){int idle=0,pr=0,co=0,rd=0,la=0,fa=0,stp=0,set=0,ab=ActBays();StringBuilder sb=new StringBuilder();sb.Append("DPS ").Append(Tag).Append("  BAYS ").Append(ab).Append("\n");for(int i=1;i<=ab;i++){Bay y=LiveB[i];int st=BayLightState(y);if(st==LS_IDLE)idle++;else if(st==LS_PRINT)pr++;else if(st==LS_COMPLETE)co++;else if(st==LS_READY)rd++;else if(st==LS_LAUNCH)la++;else if(st==LS_FAULT)fa++;else if(st==LS_STOPPED)stp++;else if(st==LS_SETUP)set++;}
sb.Append("I").Append(idle).Append(" P").Append(pr).Append(" C").Append(co).Append(" R").Append(rd).Append(" L").Append(la).Append(" F").Append(fa).Append(" S").Append(stp).Append("\n");for(int i=1;i<=ab;i++){Bay y=LiveB[i];if(y==null||!y.Core())continue;int slot=LoadedSlot[i]>0?LoadedSlot[i]:Sel[i];sb.Append(B2(i)).Append(' ').Append(SlotShort(slot)).Append(' ').Append(LightStateName(BayLightState(y))).Append("\n");}return sb.ToString();}

void Report(bool force){StringBuilder r=new StringBuilder();int dmg=0,dst=0,pj=0,li=0,lg=0,xg=0,sup=0,sens=0,ok=0,active=0;for(int i=1;i<=MAXB;i++){Bay y=B[i];if(!y.Core())continue;active++;dmg+=y.Dmg;dst+=y.Miss;pj+=y.PCtl;li+=y.LI;lg+=y.LG;xg+=y.XG;sup+=y.S;sens+=y.A;if(y.Miss==0&&y.Dmg==0&&y.PCtl==0)ok++;}
 string st=dst>0||dmg>0?"FAULT":(pj>0?"ATTN":"OK");int lx=lg+xg;LastState=st;LastBays=active;LastDmg=dmg;LastDst=dst;LastPJ=pj;LastLI=li;LastLX=lx;r.Append("[DPS REPORT]\nVersion=").Append(VERSION).Append("\nState=").Append(st).Append("\nProjectorMode=").Append(ProjectorModeText()).Append("\nBays=").Append(active).Append("\nDmg=").Append(dmg).Append("\nDstr=").Append(dst).Append("\nPJ=").Append(pj).Append("\nLI=").Append(li).Append("\nLX=").Append(lx).Append("\nHelmLCD=").Append(HelmLcds.Count).Append("\nS=").Append(sup).Append("\nO=").Append(sens).Append("\nLightStates=Feedback lane uses live accepted cache; STATUS/AUTO rebuild staging cache then swaps when complete\nPerfStageMax=").Append(DiscHi).Append("/50000 ").Append(DiscHiPhase).Append("\nPerfLastRun=").Append(Hi).Append("/50000 ").Append(HiPhase).Append("\nPerfLifetime=").Append(HiCap).Append("/50000 ").Append(HiCapPhase).Append("\nPacket=DPS|").Append(Tag).Append('|').Append(st).Append("|D=").Append(dmg).Append("|X=").Append(dst).Append("|PJ=").Append(pj).Append("\n\n[BAYS]\n");
 for(int i=1;i<=MAXB;i++){Bay y=B[i];if(!y.Core())continue;r.Append(i<10?"0":"").Append(i).Append(' ').Append(y.Miss>0||y.Dmg>0?"BAD":"OK").Append(" W").Append(y.W-y.DW).Append(" G").Append(y.G-y.DG).Append(" P").Append(y.P-y.DP).Append(" M").Append(y.M-y.DM).Append(" C").Append(y.C-y.DC).Append(" O").Append(y.A-y.DA).Append(" S").Append(y.S-y.DS).Append(" LI").Append(y.LI-y.DLI).Append(" LX").Append((y.LG-y.DLG)+y.XG).Append(" LCD").Append(y.Lcds.Count).Append(" LS:").Append(LightStateName(BayLightState(y)));if(y.PCtl>0)r.Append(" PJ!").Append(y.PCtl);if(y.Dmg>0)r.Append(" DMG").Append(y.Dmg);if(y.Miss>0)r.Append(" DES").Append(y.Miss);r.Append('\n');}
 AddBayCoreDiag(r);AddSlotAvailabilityReport(r);AddLaunchReport(r);r.Append("\n[COMMANDS]\nSee managed command block above. STATUS is optional full-state refresh. Manual exclude: [NODPS]\n");SetReport(r.ToString());IGC.SendBroadcastMessage("DPS",Tag+"|"+st+"|D"+dmg+"|X"+dst+"|PJ"+pj,TransmissionDistance.CurrentConstruct);Status=st+" D"+dmg+" X"+dst+" PJ"+pj;}

IMyTerminalBlock BayCoreAnchor(Bay y){if(y==null)return null;if(y.Wls.Count>0)return y.Wls[0];if(y.Pjs.Count>0)return y.Pjs[0];if(y.Ms.Count>0)return y.Ms[0];if(y.Cs.Count>0)return y.Cs[0];if(y.As.Count>0)return y.As[0];if(y.Sens.Count>0)return y.Sens[0];if(y.Gates.Count>0)return y.Gates[0];return null;}
void AddBayCoreDiag(StringBuilder r){int core=0,extra=0;r.Append("\n[DPS BAY CORE DIAG]\nManagedBays=").Append(ManagedBays).Append("\n");for(int i=1;i<=MAXB;i++){Bay y=B[i];if(y==null||!y.Core())continue;core++;if(i>ManagedBays)extra++;}r.Append("CoreBays=").Append(core).Append("\nExtraCoreBays=").Append(extra).Append("\n");for(int i=1;i<=MAXB;i++){Bay y=B[i];if(y==null||!y.Core())continue;IMyTerminalBlock a=BayCoreAnchor(y);r.Append("BAY").Append(B2(i)).Append(i>ManagedBays?" EXTRA ":" ").Append("W").Append(y.W).Append(" G").Append(y.G).Append(" P").Append(y.P).Append(" M").Append(y.M).Append(" C").Append(y.C).Append(" O").Append(y.A).Append(" S").Append(y.S);if(a!=null){r.Append(" Anchor=").Append(a.CustomName);IMyCubeBlock cb=a as IMyCubeBlock;if(cb!=null&&cb.CubeGrid!=null)r.Append(" GridId=").Append(cb.CubeGrid.EntityId);}else r.Append(" Anchor=-");r.Append("\n");}r.Append("Note=Core bays are counted from W/G/P/M/C/O blocks carrying a BAY## identity. EXTRA lines identify any BAY## above ManagedBays that is inflating Echo/report bay count.\n");}
void CommandReport(string cmd,string note){StringBuilder r=new StringBuilder();r.Append("[DPS COMMAND RESULT]\nVersion=").Append(VERSION).Append("\nCommand=").Append(cmd).Append("\nAutoEnabled=").Append(AutoOn?"true":"false").Append("\nPaused=").Append(Paused?"true":"false").Append("\nNote=").Append(note).Append("\nPerfLastRun=").Append(Hi).Append("/50000 ").Append(HiPhase).Append("\n");SetReport(r.ToString());}
void SetReport(string rep){Me.CustomData=CfgText()+"\n# <DPS_LAST_REPORT_BEGIN>\n"+rep+"# <DPS_LAST_REPORT_END>\n";}
void EchoOut(){Echo("DPS V183  AUTO:"+(ReviewPause?"REVIEW":(AutoOn?(Paused?"PAUSED":"ON"):"OFF")));Echo("STATE: "+LastState+"  BAYS:"+LastBays);Echo("DMG:"+LastDmg+"  DES:"+LastDst+"  PJ:"+LastPJ);Echo("LIGHTS LI:"+LastLI+"  LX:"+LastLX);string pm=ProjectorModeText();if(pm!="IDLE")Echo("PJ MODE: "+pm);if(RotAlignRun)Echo("ROTOR ALIGN t:"+RotAlignTick+" seen:"+RotAlignSeen+" lock:"+RotAlignLocked+" move:"+RotAlignMoving);if(ScanRun)Echo((ScanAuto?"AUTO":"STATUS")+" STAGE:"+ScanStage+" IDX:"+ScanIdx);if(DiscRun)Echo("DISC STAGE:"+DiscStage+" IDX:"+DiscIdx);if(AccRun)Echo("ACCEPT QUEUE BAY:"+AccBay+"/"+D_best+" JOBS:"+AccJobs);if(ApplyRun)Echo(ApplyTitle+" APPLY "+ApplyDone+"/"+ApplyTotal);if(ReviewPause)Echo("Worker Paused - review report, run AUTO");Echo("PERF run "+(Hi/1000.0).ToString("0.0")+"K max "+(HiCap/1000.0).ToString("0.0")+"K "+HiCapPhase);if(DiscRun||AccRun||ApplyRun)Echo("Command running - report updates on completion");else if(!ReviewPause)Echo("STATUS refreshes full Custom Data report");Echo("DCS REG "+DcsRegRefresh);}
void AddSlotAvailabilityReport(StringBuilder r){r.Append("\n[PROJECTOR SLOT AVAILABILITY]\n");for(int i=1;i<=ActBays();i++){Bay y=B[i];int m=ExpectedSlotMask(y);r.Append("BAY").Append(B2(i)).Append(' ');string t=SlotMaskText(m);r.Append(t.Length>0?t:"-").Append("\n");}}
void AddLaunchReport(StringBuilder r){r.Append("\n[DPS LAUNCH]\nDoorCloseDelaySeconds=").Append(F(DoorCloseDelaySec)).Append("\n");for(int i=1;i<=ActBays();i++){Bay y=B[i];if(y==null||!y.Core())continue;int o=OccupancyCount(y);r.Append("BAY").Append(B2(i)).Append(" O=").Append(o).Append(" CLEAR=").Append(o>0&&OccupancyClear(y)?"YES":(o>0?"NO":"TIMER")).Append(" Phase=").Append(LaunchPhase[i]).Append(" T=").Append(F(LaunchSec[i])).Append(" State=").Append(LightStateName(BayState[i])).Append("\n");}}
string SlotShort(int s){if(s>0&&s<=MAXS&&SS[s]!="")return SS[s];return "PJ"+B2(s);}string Clip(string s,int n){if(s==null)return"";return s.Length<=n?s:s.Substring(0,n);}
string ProjectorModeText(){if(SetupBay>0)return"SETUP BAY"+B2(SetupBay)+" PJ"+B2(SetupSlot);if(ShowSlot>0)return"SHOW PJ"+B2(ShowSlot);int p=0,cp=0,rd=0,la=0,st=0;for(int i=1;i<=MAXB;i++){if(BayState[i]==LS_PRINT)p++;if(BayState[i]==LS_COMPLETE)cp++;if(BayState[i]==LS_READY)rd++;if(BayState[i]==LS_LAUNCH)la++;if(BayState[i]==LS_STOPPED)st++;}if(p>0)return"PRINT "+p+" BAY"+(p==1?"":"S");if(cp>0)return"COMPLETE "+cp+" BAY"+(cp==1?"":"S");if(rd>0)return"READY "+rd+" BAY"+(rd==1?"":"S");if(la>0)return"LAUNCH "+la+" BAY"+(la==1?"":"S");if(st>0)return"STOPPED "+st+" BAY"+(st==1?"":"S");return"IDLE";}

bool InBox(Bay y,Vector3D p,double pad,bool openEnd){double x0=y.Min.X-pad,x1=y.Max.X+pad,y0=y.Min.Y-pad,y1=y.Max.Y+pad,z0=y.Min.Z-pad,z1=y.Max.Z+pad;if(openEnd){if(y.BayAxis==0)x1=y.Max.X+1+pad;else if(y.BayAxis==1)y1=y.Max.Y+1+pad;else z1=y.Max.Z+1+pad;}return p.X>=x0&&p.X<=x1&&p.Y>=y0&&p.Y<=y1&&p.Z>=z0&&p.Z<=z1;}
bool InOut(Bay y,Vector3D p){if(InBox(y,p,0.05,true))return false;double x0=y.Min.X-0.05,x1=y.Max.X+0.05,y0=y.Min.Y-0.05,y1=y.Max.Y+0.05,z0=y.Min.Z-0.05,z1=y.Max.Z+0.05;if(y.BayAxis==0)x1=y.Max.X+1.05;else if(y.BayAxis==1)y1=y.Max.Y+1.05;else z1=y.Max.Z+1.05;double c=Axis(y.Ctr,y.OutAxis),sg=c>=y.CenterLine?1:-1;if(y.OutAxis==0){if(sg>0)x1+=2;else x0-=2;}else if(y.OutAxis==1){if(sg>0)y1+=2;else y0-=2;}else{if(sg>0)z1+=2;else z0-=2;}return p.X>=x0&&p.X<=x1&&p.Y>=y0&&p.Y<=y1&&p.Z>=z0&&p.Z<=z1;}
Vector3D LP(IMyCubeBlock b){Vector3I p=b.Position;return new Vector3D(p.X,p.Y,p.Z);}double Axis(Vector3D p,int a){return a==0?p.X:(a==1?p.Y:p.Z);}int PjSlot(IMyProjector p){string n=p.CustomName.ToUpper();for(int i=0;i<n.Length-2;i++){if(n[i]=='P'&&n[i+1]=='J'){int v=NumAt(n,i+2);if(v>0)return v;}}int k=n.IndexOf("PROJECTOR ");if(k>=0){int v=NumAt(n,k+10);if(v>0)return v;}return 1;}
int SlotFrom(string s){s=s.ToUpper().Trim();if(s.StartsWith("PJ")){int v=NumAt(s,2);if(v>0&&v<=MAXS)return v;}for(int i=1;i<=MAXS;i++)if(SR[i]!=""&&(s==SR[i]||s==SS[i]||s==SL[i].ToUpper()))return i;return 0;}
int SlotAfterBay(string u){int i=u.IndexOf("BAY");if(i<0)return 0;i+=3;while(i<u.Length&&char.IsDigit(u[i]))i++;return SlotFrom(u.Substring(i).Trim());}
string Name(int bay,string role,int n){return Tag+" "+SYS+" [BAY"+(bay<10?"0":"")+bay+"] "+role+" "+(n<10?"0":"")+n;}

int BayNum(string s){if(s==null)return 0;string u=s.ToUpper();int i=u.IndexOf("BAY");while(i>=0){int v=NumAt(u,i+3);if(v>0)return v;i=u.IndexOf("BAY",i+3);}return 0;}
int NumAt(string s,int i){int v=0;while(i<s.Length&&!char.IsDigit(s[i]))i++;while(i<s.Length&&char.IsDigit(s[i])){v=v*10+(s[i]-'0');i++;}return v;}
bool Has(string s,string t){return s!=null&&s.IndexOf(t,StringComparison.OrdinalIgnoreCase)>=0;}bool Ex(IMyTerminalBlock b){return b==null||Has(b.CustomName,NO);}bool Foreign(string n){if(n==null)return false;if(Has(n,Tag)||Has(n,SYS)||Has(n,"[BAY"))return false;if(n.Length<2||n[0]!='[')return false;int e=n.IndexOf(']');if(e<0)return false;string t=n.Substring(0,e+1);if(t==Tag||t==SYS||t.StartsWith("[BAY"))return false;return true;}
string Val(string cd,string key){int i=cd.IndexOf(key,StringComparison.OrdinalIgnoreCase);if(i<0)return"";i+=key.Length;int e=cd.IndexOf('\n',i);if(e<0)e=cd.Length;return cd.Substring(i,e-i).Trim();}int IVal(string cd,string key,int d){string v=Val(cd,key);int n;if(int.TryParse(v.Replace("PJ",""),out n))return n;return d;}

class Bay{public int N,W,G,P,M,C,A,S,LI,LG,XG,Dmg,Miss,PCtl,DW,DG,DP,DM,DC,DA,DS,DLI,DLG,BayAxis=2,OutAxis=1;public bool Ready=false;public double CenterLine=0;public Vector3D Min,Max,Ctr;public IMyCubeGrid Grid;public List<IMyCubeBlock> Ws=new List<IMyCubeBlock>();public List<IMyShipWelder> Wls=new List<IMyShipWelder>();public List<IMyDoor> Gates=new List<IMyDoor>();public List<IMyProjector>Pjs=new List<IMyProjector>();public List<IMyShipMergeBlock> Ms=new List<IMyShipMergeBlock>();public List<IMyShipConnector> Cs=new List<IMyShipConnector>();public List<IMyCameraBlock> As=new List<IMyCameraBlock>();public List<IMySensorBlock> Sens=new List<IMySensorBlock>();public List<IMyLightingBlock> Lts=new List<IMyLightingBlock>();public List<IMyTextPanel> Lcds=new List<IMyTextPanel>();public Bay(int n){N=n;}public void Clr(){W=G=P=M=C=A=S=LI=LG=XG=Dmg=Miss=PCtl=DW=DG=DP=DM=DC=DA=DS=DLI=DLG=0;Ready=false;Grid=null;Ws.Clear();Wls.Clear();Gates.Clear();Pjs.Clear();Ms.Clear();Cs.Clear();As.Clear();Sens.Clear();Lts.Clear();Lcds.Clear();}public bool Any(){return W+G+P+M+C+A+S+LI+LG+XG>0;}public bool Core(){return W+G+P+M+C+A>0;}public void AddW(IMyCubeBlock b){if(b!=null){Ws.Add(b);Grid=b.CubeGrid;}}public void Bounds(){if(Ws.Count==0)return;Vector3D p=Vec(Ws[0]);Min=Max=p;for(int i=1;i<Ws.Count;i++){p=Vec(Ws[i]);Min=new Vector3D(Math.Min(Min.X,p.X),Math.Min(Min.Y,p.Y),Math.Min(Min.Z,p.Z));Max=new Vector3D(Math.Max(Max.X,p.X),Math.Max(Max.Y,p.Y),Math.Max(Max.Z,p.Z));}Ctr=(Min+Max)/2;Ready=true;}Vector3D Vec(IMyCubeBlock b){Vector3I p=b.Position;return new Vector3D(p.X,p.Y,p.Z);}}
class DCl{public IMyCubeGrid G;public Vector3D W,Mn,Mx;public int N;public List<Vector3I> AC=new List<Vector3I>();}
class RenameJob{public IMyTerminalBlock B;public string N;public RenameJob(IMyTerminalBlock b,string n){B=b;N=n;}}
