// LDC1 DCS V015 WSS SEED RECEIVE
// Adds upstream seed waypoint proof: receive WSS seed packet, display it, and write current fresh seed into drone Vector= assignment.
// Scope: no wave launch, no connector release, no drone flight control. Custody AI blocks stay OFF; no AI behavior/action spam.

const string VERSION="LDC1_DCS_V015_WssSeedReceive";
const string DEF_TAG="[LDC1]",SYS="[DCS]",NO="[NODCS]";
const string DRONE_IGC="DRONE",WSS_IGC="WSS",WSS_SEED_IGC="WSS_SEED";
const string SVC_BEGIN="# <DCS_SERVICE_BEGIN>",SVC_END="# <DCS_SERVICE_END>";
const int MAXB=20,MAXS=9,SEED_MAX_AGE=6;

string Tag=DEF_TAG,Mode="LOCAL",Wave="A",Status="Idle",LastDroneMsg="",LastSeedMsg="";
string SeedVector="",SeedSource="NONE"; int SeedSeq=0,SeedAge=9999;
int Tick=0,Hi=0,HiCap=0; string HiPhase="INIT",HiCapPhase="INIT";
double ClearForwardMeters=50,ClearForwardSpeed=5,SeparationMeters=4,LaneStepDelaySec=0,FanMeters=80;

List<IMyTerminalBlock> All=new List<IMyTerminalBlock>();
List<IMyTextPanel> Lcds=new List<IMyTextPanel>();
List<IMyProgrammableBlock> DpsPbs=new List<IMyProgrammableBlock>();
List<IMyProgrammableBlock> Pbs=new List<IMyProgrammableBlock>();
List<IMyTerminalBlock> GridBlocks=new List<IMyTerminalBlock>();
List<IMyTerminalBlock> BayAnchors=new List<IMyTerminalBlock>();
List<IMyProgrammableBlock> CandPbs=new List<IMyProgrammableBlock>();
List<IMyProgrammableBlock> RejTaggedPbs=new List<IMyProgrammableBlock>();
List<IMyShipMergeBlock> CandMerges=new List<IMyShipMergeBlock>();
IMyBroadcastListener DroneListen,WssListen,WssSeedListen;
BayReg[] Bays=new BayReg[MAXB+1];

public Program(){for(int i=0;i<Bays.Length;i++)Bays[i]=new BayReg(i);LoadCfg();DroneListen=IGC.RegisterBroadcastListener(DRONE_IGC);DroneListen.SetMessageCallback("IGC");WssListen=IGC.RegisterBroadcastListener(WSS_IGC);WssListen.SetMessageCallback("IGC");WssSeedListen=IGC.RegisterBroadcastListener(WSS_SEED_IGC);WssSeedListen.SetMessageCallback("IGC");Runtime.UpdateFrequency=UpdateFrequency.Update100;Scan();}
public void Save(){EnsureCfg();}
public void Main(string arg,UpdateType src){Upd("START");string a=arg==null?"":arg.Trim();if(a=="IGC"||(src&UpdateType.IGC)!=0){ReadIgc();AutoServiceAccepted();UpdateDisplays();EchoOut();Upd("END");return;}if(a.Length>0)Cmd(a);else{ReadIgc();Tick++;if(Tick>=3){Tick=0;Scan();}else UpdateDisplays();AutoServiceAccepted();}EchoOut();Upd("END");}

void Cmd(string a){string u=a.ToUpper().Trim();Status="Command "+a;if(u=="STATUS"){ReadIgc();Scan();WriteStatusReport(0);return;}if(u=="SCAN"||u=="REFRESH"){Scan();return;}if(u=="SEED STATUS"){ReadIgc();WriteSeedReport();return;}if(u=="SEED CLEAR"){SeedVector="";SeedSource="NONE";SeedSeq=0;SeedAge=9999;Status="Seed cleared";WriteSeedReport();return;}if(u.StartsWith("REG ")){RegCmd(u);return;}Status="Unknown command";}
void RegCmd(string u){if(u.StartsWith("REG DRYRUN ALL")){Scan();for(int i=1;i<=MAXB;i++)DryRun(i,false);WriteRegReport(0,"DRYRUN ALL",false);return;}if(u.StartsWith("REG STATUS ALL")){Scan();WriteStatusReport(0);return;}int b=BayNum(u);if(b<1||b>MAXB){Status="REG needs BAY##";return;}if(u.StartsWith("REG DRYRUN")){Scan();DryRun(b,true);return;}if(u.StartsWith("REG ACCEPT")){Scan();ReadIgc();RegAccept(b);return;}if(u.StartsWith("REG SERVICE")){Scan();ReadIgc();RegService(b,true);return;}if(u.StartsWith("REG STATUS")){Scan();WriteStatusReport(b);return;}if(u.StartsWith("REG CLEAR")){RegClear(b);return;}Status="Unknown REG command";}

void LoadCfg(){string cd=Me.CustomData;string t=Val(cd,"Tag=");if(t!="")Tag=t;string m=Val(cd,"Mode=");if(m!="")Mode=m;string w=Val(cd,"Wave=");if(w!="")Wave=w.Trim().ToUpper();double x=ToD(Val(cd,"ClearForwardMeters="));if(x>0)ClearForwardMeters=x;x=ToD(Val(cd,"ClearForwardSpeed="));if(x>0)ClearForwardSpeed=x;x=ToD(Val(cd,"SeparationMeters="));if(x>0)SeparationMeters=x;x=ToD(Val(cd,"LaneStepDelaySec="));if(x>=0)LaneStepDelaySec=x;x=ToD(Val(cd,"FanMeters="));if(x>0)FanMeters=x;LoadAcceptedRegs(cd);EnsureCfg();}
void EnsureCfg(){if(Me.CustomData.Contains("[ENTITY]")&&Me.CustomData.Contains("[Departure]")&&Me.CustomData.Contains("[REGISTRATION]"))return;Me.CustomData=CfgText()+"\n"+ManagedTail(Me.CustomData);}
string ManagedTail(string cd){int i=cd.IndexOf("# <DCS_LAST_REPORT_BEGIN>");return i>=0?cd.Substring(i):"";}
string CfgText(){StringBuilder s=new StringBuilder();s.Append("[ENTITY]\nTag=").Append(Tag).Append("\nSystem=DCS\n\n");s.Append("[DCS]\nMode=").Append(Mode).Append("\n\n");s.Append("[REGISTRATION]\nWave=").Append(Wave).Append("\n");s.Append("Note=REG is a temporary/manual developer surface. Mature flow should auto-register from DPS print state.\n\n");s.Append("[Departure]\nClearForwardMeters=").Append(F(ClearForwardMeters)).Append("\nClearForwardSpeed=").Append(F(ClearForwardSpeed)).Append("\nSeparationMeters=").Append(F(SeparationMeters)).Append("\nLaneStepDelaySec=").Append(F(LaneStepDelaySec)).Append("\nFanMeters=").Append(F(FanMeters)).Append("\n\n");AppendAcceptedCfg(s);AppendSvcPacket(s);s.Append("# <DCS_COMMANDS_BEGIN>\n[DCS COMMANDS]\nREG DRYRUN BAY##|ALL\nREG ACCEPT BAY##\nREG SERVICE BAY##\nREG STATUS BAY##|ALL\nREG CLEAR BAY##\nSEED STATUS\nSEED CLEAR\nSTATUS; SCAN\n# <DCS_COMMANDS_END>\n");return s.ToString();}

void AppendAcceptedCfg(StringBuilder s){s.Append("[REG ACCEPTED]\n");bool any=false;for(int i=1;i<=MAXB;i++){BayReg y=Bays[i];if(y==null)continue;if(!y.Accepted&&y.Serial==""&&!y.ServiceDone&&y.ServiceSeq<1)continue;string k="Bay"+B2(i)+".";s.Append(k).Append("Accepted=").Append(y.Accepted?"YES":"NO").Append("\n");s.Append(k).Append("ServiceDone=").Append(y.ServiceDone?"YES":"NO").Append("\n");if(y.ServiceSeq>0)s.Append(k).Append("ServiceSeq=").Append(y.ServiceSeq).Append("\n");if(y.Serial!="")s.Append(k).Append("Serial=").Append(y.Serial).Append("\n");if(y.State!="")s.Append(k).Append("State=").Append(y.State).Append("\n");any=true;}if(!any)s.Append("; none\n");s.Append("\n");}
void AppendSvcPacket(StringBuilder s){s.Append(SVC_BEGIN).Append("\n[DCS SERVICE]\nVersion=").Append(VERSION).Append("\n");int any=0;for(int i=1;i<=MAXB;i++){BayReg y=Bays[i];if(y==null||y.ServiceSeq<1)continue;string k="BAY"+B2(i);s.Append(k).Append(".ServiceLockedSeq=").Append(y.ServiceSeq).Append("\n");if(y.Serial!="")s.Append(k).Append(".Serial=").Append(y.Serial).Append("\n");if(y.State!="")s.Append(k).Append(".State=").Append(y.State).Append("\n");any++;}if(any==0)s.Append("; none\n");s.Append(SVC_END).Append("\n\n");}
void LoadAcceptedRegs(string cd){for(int i=1;i<=MAXB;i++){string k="Bay"+B2(i)+".";string a=Val(cd,k+"Accepted=");string d=Val(cd,k+"ServiceDone=");string ser=Val(cd,k+"Serial=");string st=Val(cd,k+"State=");int ss=ToInt(Val(cd,k+"ServiceSeq="));if(ss>0)Bays[i].ServiceSeq=ss;if(a!="")Bays[i].Accepted=a.ToUpper().StartsWith("Y");if(d!="")Bays[i].ServiceDone=d.ToUpper().StartsWith("Y");if(ser!="")Bays[i].Serial=ser;if(st!="")Bays[i].State=st;}}

void Scan(){LoadCfg();All.Clear();Lcds.Clear();DpsPbs.Clear();Pbs.Clear();GridTerminalSystem.GetBlocksOfType<IMyTerminalBlock>(All);for(int i=0;i<All.Count;i++){IMyTerminalBlock b=All[i];if(b==null||Has(b.CustomName,NO))continue;IMyTextPanel p=b as IMyTextPanel;if(p!=null&&Has(b.CustomName,SYS))Lcds.Add(p);IMyProgrammableBlock pb=b as IMyProgrammableBlock;if(pb!=null){Pbs.Add(pb);if(Has(pb.CustomName,"[DPS]"))DpsPbs.Add(pb);}}ReadDpsMeta();UpdateDisplays();Status="Scan complete";}
void ReadDpsMeta(){for(int i=1;i<=MAXB;i++){Bays[i].DpsState="";Bays[i].Slot=0;Bays[i].NextSlot=0;}for(int p=0;p<DpsPbs.Count;p++){string cd=DpsPbs[p].CustomData;for(int s=1;s<=MAXS;s++){string k="PJ"+B2(s);string r=Val(cd,k+".Role="),sh=Val(cd,k+".Short=");if(r!="")Role[s]=r.Trim();if(sh!="")Short[s]=sh.Trim().ToUpper();}for(int b=1;b<=MAXB;b++){string k="BAY"+B2(b);int nx=SlotFrom(Val(cd,k+"="));if(nx>0)Bays[b].NextSlot=nx;int ld=SlotFrom(Val(cd,k+".Loaded="));if(ld>0)Bays[b].Slot=ld;else if(nx>0)Bays[b].Slot=nx;string st=Val(cd,k+".State=");if(st!="")Bays[b].DpsState=st;}}}
string[] Role=new string[MAXS+1]; string[] Short=new string[MAXS+1];

void DryRun(int b,bool write){BayReg y=Bays[b];DiscoverBay(b,y);BuildAssignment(y,false);if(write)WriteRegReport(b,"DRYRUN",false);}
void RegAccept(int b){BayReg y=Bays[b];DiscoverBay(b,y);BuildAssignment(y,false);if(!y.Clean){Status="REG ACCEPT blocked; review DRYRUN";WriteRegReport(b,"ACCEPT BLOCKED",true);return;}y.Pb.Enabled=true;WriteAssignment(y);EnforceCaptive(y);try{y.Pb.TryRun("BOOT");}catch{}y.Accepted=true;y.ServiceDone=false;Status="REG ACCEPT BAY"+B2(b)+" "+y.Serial+" waiting heartbeat";WriteRegReport(b,"ACCEPT",true);}
void RegClear(int b){BayReg y=Bays[b];y.Serial="";y.State="";y.Heartbeat=false;y.Accepted=false;y.ServiceDone=false;y.Age=9999;y.Fault="";y.ServiceSeq=0;Status="REG CLEAR BAY"+B2(b);WriteStatusReport(b);}
void RewriteCfgKeepReport(){string cd=Me.CustomData;string rep="";int i=cd.IndexOf("# <DCS_LAST_REPORT_BEGIN>");if(i>=0)rep=cd.Substring(i);Me.CustomData=CfgText()+"\n"+rep;}

void DiscoverBay(int b,BayReg y){y.ClearRuntime();BayAnchors.Clear();CandPbs.Clear();RejTaggedPbs.Clear();CandMerges.Clear();string bt="[BAY"+B2(b)+"]";for(int i=0;i<All.Count;i++){IMyTerminalBlock x=All[i];if(x==null)continue;if(Has(x.CustomName,bt)&&!Has(x.CustomName,NO)){BayAnchors.Add(x);IMyShipMergeBlock mg=x as IMyShipMergeBlock;if(mg!=null)CandMerges.Add(mg);}}IMyCubeGrid iface=null;if(CandMerges.Count==1){y.Merge=CandMerges[0];iface=y.Merge.CubeGrid;y.InterfaceGridId=iface.EntityId;}if(iface!=null){for(int i=0;i<Pbs.Count;i++){IMyProgrammableBlock pb=Pbs[i];if(pb==null||pb==Me)continue;if(pb.CubeGrid!=iface)continue;if(HasAnyTag(pb.CustomName)){RejTaggedPbs.Add(pb);continue;}CandPbs.Add(pb);}}y.AnchorCount=BayAnchors.Count;y.PbCount=CandPbs.Count;y.RejTaggedCount=RejTaggedPbs.Count;y.MergeCount=CandMerges.Count;if(CandPbs.Count==1)y.Pb=CandPbs[0];y.CandDetail=BuildCandidateDetail();y.RejDetail=BuildRejectedTaggedDetail();string why="";if(y.MergeCount==0)why+="NO_BAY_MERGE ";if(y.MergeCount>1)why+="MULTI_BAY_MERGE ";if(y.Slot<=0)why+="NO_DPS_SLOT ";if(iface==null)why+="NO_INTERFACE_GRID ";if(iface!=null&&y.PbCount==0)why+="NO_UNTAGGED_PB_ON_INTERFACE_GRID ";if(y.PbCount>1)why+="MULTI_UNTAGGED_PB_ON_INTERFACE_GRID ";y.Clean=why=="";y.Fault=why.Trim();}
string BuildRejectedTaggedDetail(){StringBuilder s=new StringBuilder();if(RejTaggedPbs.Count==0)return"";for(int i=0;i<RejTaggedPbs.Count;i++){IMyProgrammableBlock pb=RejTaggedPbs[i];s.Append("PB").Append(B2(i+1)).Append("\n");s.Append("  Name=").Append(pb.CustomName).Append("\n");s.Append("  GridId=").Append(pb.CubeGrid.EntityId).Append("\n");s.Append("  Reason=PB_HAS_BRACKET_TAG\n");s.Append("  Evidence=").Append(CandidateEvidence(pb)).Append("\n");}return s.ToString();}
bool HasAnyTag(string name){if(name==null)return false;int a=name.IndexOf('[');if(a<0)return false;int b=name.IndexOf(']',a+1);return b>a;}
string BuildCandidateDetail(){StringBuilder s=new StringBuilder();if(CandPbs.Count==0)return"";for(int i=0;i<CandPbs.Count;i++){IMyProgrammableBlock pb=CandPbs[i];s.Append("PB").Append(B2(i+1)).Append("\n");s.Append("  Name=").Append(pb.CustomName).Append("\n");s.Append("  GridId=").Append(pb.CubeGrid.EntityId).Append("\n");s.Append("  Score=").Append(CandidateScore(pb)).Append("\n");s.Append("  Evidence=").Append(CandidateEvidence(pb)).Append("\n");}return s.ToString();}
int CandidateScore(IMyProgrammableBlock pb){int sc=0;string ev=CandidateEvidence(pb);if(ev.Contains("AIF"))sc+=2;if(ev.Contains("AIO"))sc+=2;if(ev.Contains("ANT"))sc++;if(ev.Contains("CON"))sc++;if(ev.Contains("MRG"))sc++;if(ev.Contains("THR"))sc++;if(ev.Contains("GYR"))sc++;if(ev.Contains("BAT"))sc++;if(ev.Contains("H2"))sc++;if(!Has(pb.CustomName,Tag))sc++;return sc;}
string CandidateEvidence(IMyProgrammableBlock pb){int aif=0,aio=0,ant=0,con=0,mrg=0,thr=0,gyr=0,bat=0,h2=0;IMyCubeGrid g=pb.CubeGrid;for(int i=0;i<All.Count;i++){IMyTerminalBlock b=All[i];if(b==null||b.CubeGrid!=g)continue;if(IsAiFlight(b))aif++;else if(IsAiOff(b))aio++;else if(b is IMyRadioAntenna)ant++;else if(b is IMyShipConnector)con++;else if(b is IMyShipMergeBlock)mrg++;else if(b is IMyThrust)thr++;else if(b is IMyGyro)gyr++;else if(b is IMyBatteryBlock)bat++;else if(b is IMyGasTank)h2++;}StringBuilder s=new StringBuilder();if(aif>0)s.Append("AIF").Append(aif).Append(' ');if(aio>0)s.Append("AIO").Append(aio).Append(' ');if(ant>0)s.Append("ANT").Append(ant).Append(' ');if(con>0)s.Append("CON").Append(con).Append(' ');if(mrg>0)s.Append("MRG").Append(mrg).Append(' ');if(thr>0)s.Append("THR").Append(thr).Append(' ');if(gyr>0)s.Append("GYR").Append(gyr).Append(' ');if(bat>0)s.Append("BAT").Append(bat).Append(' ');if(h2>0)s.Append("H2").Append(h2).Append(' ');return s.ToString().Trim();}
bool IsAiFlight(IMyTerminalBlock b){string s=(b.BlockDefinition.TypeIdString+"/"+b.BlockDefinition.SubtypeName).ToUpper();return s.Contains("FLIGHTMOVEMENT")||s.Contains("FLIGHT");}
bool IsAiOff(IMyTerminalBlock b){string s=(b.BlockDefinition.TypeIdString+"/"+b.BlockDefinition.SubtypeName).ToUpper();return s.Contains("OFFENSIVE");}

void BuildAssignment(BayReg y,bool preserve){int s=y.Slot;string sh=(s>0&&s<=MAXS&&Short[s]!="")?Short[s]:"D";string ro=(s>0&&s<=MAXS&&Role[s]!="")?Role[s]:"DRONE";y.Short=sh;y.Role=ro;y.Wave=Wave;y.Serial=sh+Wave+B2(y.N);y.Departure=DepartureFor(y.N);y.Vector=SeedFresh()?SeedVector:"";}
string DepartureFor(int bay){int lane=(bay%2==1)?-((bay+1)/2):(bay/2);double off=lane*SeparationMeters;double delay=Math.Abs(lane)*LaneStepDelaySec;StringBuilder s=new StringBuilder();s.Append("F:").Append(F(ClearForwardMeters)).Append('@').Append(F(ClearForwardSpeed));s.Append(",O:").Append(F(off));if(delay>0)s.Append(",D:").Append(F(delay));s.Append(",Fan:").Append(F(FanMeters)).Append(",VECTOR");return s.ToString();}
void WriteAssignment(BayReg y){if(y.Pb==null)return;StringBuilder a=new StringBuilder();a.Append("[DRONE_ASSIGN]\n");a.Append("Origin=").Append(CleanTag(Tag)).Append('\n');a.Append("Serial=").Append(y.Serial).Append('\n');a.Append("Role=").Append(y.Role).Append('\n');a.Append("Short=").Append(y.Short).Append('\n');a.Append("Wave=").Append(y.Wave).Append('\n');a.Append("Bay=").Append(y.N).Append('\n');a.Append("Slot=PJ").Append(B2(y.Slot)).Append('\n');a.Append("Departure=").Append(y.Departure).Append('\n');a.Append("Vector=").Append(y.Vector).Append("\nAssignedBy=DCS\n");y.Pb.CustomData=RenderDronePbData(a.ToString(),GetSection(y.Pb.CustomData,"[DRONE_STATUS]"));}
string RenderDronePbData(string assign,string status){StringBuilder s=new StringBuilder();if(assign!=null&&assign.Trim().Length>0)s.Append(assign.Trim()).Append("\n");if(status!=null&&status.Trim().Length>0)s.Append("\n").Append(status.Trim()).Append("\n");return s.ToString();}
string GetSection(string cd,string header){if(cd==null)return"";int a=cd.IndexOf(header);if(a<0)return"";int n=cd.IndexOf("\n[",a+header.Length);if(n<0)n=cd.Length;return cd.Substring(a,n-a).Trim()+"\n";}

void EnforceCaptive(BayReg y){if(y.Pb==null)return;GridBlocks.Clear();IMyCubeGrid g=y.Pb.CubeGrid;GridTerminalSystem.GetBlocksOfType<IMyTerminalBlock>(GridBlocks);for(int i=GridBlocks.Count-1;i>=0;i--){if(GridBlocks[i]==null||GridBlocks[i].CubeGrid!=g)GridBlocks.RemoveAt(i);}for(int i=0;i<GridBlocks.Count;i++){IMyTerminalBlock b=GridBlocks[i];IMyProgrammableBlock pb=b as IMyProgrammableBlock;if(pb!=null){try{if(!pb.Enabled)pb.Enabled=true;}catch{}continue;}IMyBatteryBlock bat=b as IMyBatteryBlock;if(bat!=null){try{if(bat.ChargeMode!=ChargeMode.Recharge)bat.ChargeMode=ChargeMode.Recharge;}catch{}continue;}IMyGasTank tank=b as IMyGasTank;if(tank!=null){try{if(!tank.Stockpile)tank.Stockpile=true;}catch{}continue;}IMyThrust th=b as IMyThrust;if(th!=null){try{if(th.ThrustOverridePercentage!=0f)th.ThrustOverridePercentage=0f;if(th.Enabled)th.Enabled=false;}catch{}continue;}IMyGyro gy=b as IMyGyro;if(gy!=null){try{if(gy.GyroOverride)gy.GyroOverride=false;if(gy.Enabled)gy.Enabled=false;}catch{}continue;}if(IsAiBlock(b)){SafeAi(b as IMyFunctionalBlock);continue;}IMyRadioAntenna an=b as IMyRadioAntenna;if(an!=null){try{if(!an.Enabled)an.Enabled=true;if(!an.EnableBroadcasting)an.EnableBroadcasting=true;}catch{}continue;}}}
void SafeAi(IMyFunctionalBlock f){if(f==null)return;try{if(f.Enabled)f.Enabled=false;}catch{}}
void TryAct(IMyTerminalBlock b,string a){try{b.ApplyAction(a);}catch{}}
bool IsAiBlock(IMyTerminalBlock b){if(!(b is IMyFunctionalBlock))return false;string s=(b.BlockDefinition.TypeIdString+"/"+b.BlockDefinition.SubtypeName).ToUpper();return s.Contains("OFFENSIVE")||s.Contains("FLIGHTMOVEMENT")||s.Contains("FLIGHT");}

void AutoServiceAccepted(){for(int i=1;i<=MAXB;i++)RegService(i,false);}
void RegService(int i,bool forceReport){BayReg y=Bays[i];if(!y.Accepted){if(forceReport){Status="REG SERVICE BAY"+B2(i)+" blocked: not accepted";WriteRegReport(i,"SERVICE BLOCKED",true);}return;}if(!y.Heartbeat){if(forceReport){Status="REG SERVICE BAY"+B2(i)+" waiting heartbeat";WriteRegReport(i,"SERVICE WAIT",true);}return;}if(y.ServiceDone){if(forceReport){Status="REG SERVICE BAY"+B2(i)+" already done";WriteRegReport(i,"SERVICE STATUS",true);}return;}if(y.Merge==null){DiscoverBay(i,y);BuildAssignment(y,false);}if(y.Merge==null){Status="REG SERVICE BAY"+B2(i)+" no merge";if(forceReport)WriteRegReport(i,"SERVICE FAULT",true);return;}try{y.Merge.Enabled=false;}catch{}TryAct(y.Merge,"OnOff_Off");y.ServiceDone=true;RewriteCfgKeepReport();Status="REG SERVICE MERGE OFF BAY"+B2(i)+" "+y.Serial;if(forceReport)WriteRegReport(i,"SERVICE",true);}

void ReadIgc(){ReadDroneIgc();ReadSeedIgc(WssListen,"WSS");ReadSeedIgc(WssSeedListen,"WSS_SEED");}
void ReadDroneIgc(){while(DroneListen!=null&&DroneListen.HasPendingMessage){MyIGCMessage m=DroneListen.AcceptMessage();LastDroneMsg=m.Data.ToString();ParseDroneMsg(LastDroneMsg);}}
void ReadSeedIgc(IMyBroadcastListener l,string src){while(l!=null&&l.HasPendingMessage){MyIGCMessage m=l.AcceptMessage();LastSeedMsg=m.Data.ToString();ParseSeedMsg(LastSeedMsg,src);}}
void ParseSeedMsg(string msg,string src){string v=SeedFrom(msg);if(v=="")return;int q=ToInt(ValSemi(msg,"Seq="));if(q<1)q=SeedSeq+1;SeedSeq=q;SeedVector=v;SeedSource=src;SeedAge=0;Status="WSS seed RX "+src+" seq "+SeedSeq;}
string SeedFrom(string msg){string v=ValSemi(msg,"Vector=");if(v=="")v=ValSemi(msg,"Seed=");if(v=="")v=ValSemi(msg,"Waypoint=");if(v=="")v=ValSemi(msg,"WP=");if(v!="")return CleanVec(v);string x=ValSemi(msg,"X="),y=ValSemi(msg,"Y="),z=ValSemi(msg,"Z=");if(x!=""&&y!=""&&z!="")return CleanVec(x+","+y+","+z);return"";}
string CleanVec(string v){return v.Replace("(","").Replace(")","").Replace(" ","").Trim();}
bool SeedFresh(){return SeedVector!=""&&SeedAge<=SEED_MAX_AGE;}
string SeedState(){if(SeedVector=="")return"NO SEED";return SeedFresh()?"RX OK":"STALE";}

void ParseDroneMsg(string msg){string serial=ValSemi(msg,"Serial=");int bay=ToInt(ValSemi(msg,"Bay="));if(bay<1||bay>MAXB)return;BayReg y=Bays[bay];bool persist=false;y.Serial=serial;y.State=ValSemi(msg,"State=");y.Heartbeat=true;y.Age=0;y.Bat=ToInt(ValSemi(msg,"BAT="));y.H2=ToInt(ValSemi(msg,"H2="));y.Fault=ValSemi(msg,"Fault=");if(serial!=""&&!y.Accepted){y.Accepted=true;persist=true;}if(y.State=="SERVICE_LOCKED"){if(!y.ServiceDone){y.ServiceDone=true;persist=true;}if(y.ServiceSeq<1){y.ServiceSeq=NextSvcSeq();persist=true;}}if(persist)RewriteCfgKeepReport();}
int NextSvcSeq(){int m=0;for(int i=1;i<=MAXB;i++)if(Bays[i].ServiceSeq>m)m=Bays[i].ServiceSeq;return m+1;}
void UpdateDisplays(){if(SeedVector!=""&&SeedAge<9999)SeedAge++;for(int i=1;i<=MAXB;i++)if(Bays[i].Heartbeat&&Bays[i].Age<9999)Bays[i].Age++;string msg=BuildText();for(int i=0;i<Lcds.Count;i++){try{Lcds[i].ContentType=ContentType.TEXT_AND_IMAGE;Lcds[i].Alignment=TextAlignment.RIGHT;Lcds[i].FontSize=0.72f;Lcds[i].WriteText(msg,false);}catch{}}}
string BuildText(){StringBuilder sb=new StringBuilder();sb.Append("DCS ").Append(Tag).Append(" V015\n");sb.Append("W").Append(Wave).Append(" SEP").Append(F(SeparationMeters)).Append(" DPS").Append(DpsPbs.Count).Append("\n");sb.Append("SEED ").Append(SeedState()).Append(" S").Append(SeedSeq).Append(" A").Append(SeedAge).Append("\n");int shown=0;for(int i=1;i<=MAXB;i++){BayReg y=Bays[i];if(y.Serial==""&&!y.Heartbeat&&!y.Accepted)continue;shown++;sb.Append("B").Append(B2(i)).Append(' ');sb.Append(y.Serial==""?"-":y.Serial).Append(' ');sb.Append(StateCode(y.State,y.Heartbeat)).Append(' ');if(y.Heartbeat){sb.Append("B").Append(y.Bat).Append(" H").Append(y.H2).Append(" HB").Append(y.Age);}else sb.Append("NOHB");sb.Append("\n");}if(shown==0)sb.Append("NO DRONES\n");return sb.ToString();}
string StateCode(string st,bool hb){if(st==null||st=="")return hb?"HEART":"WAIT";string u=st.ToUpper();if(u.StartsWith("SERVICE"))return"SERVICE";if(u.StartsWith("MERGED"))return"MERGED";if(u.StartsWith("READY"))return"READY";if(u.StartsWith("LAUNCH"))return"LAUNCH";if(u.StartsWith("DEPART"))return"DEPART";if(u.StartsWith("VECTOR"))return"VECTOR";if(u.StartsWith("ASSIGN"))return"ASSIGN";if(u.StartsWith("FAULT"))return"FAULT";if(u.Length<=7)return u;return u.Substring(0,7);}

void WriteRegReport(int b,string title,bool includeActions){StringBuilder r=new StringBuilder();r.Append("[DCS REG ").Append(title).Append("]\nVersion=").Append(VERSION).Append("\nNote=REG is temporary/manual. Mature flow should auto-run from DPS print completion.\n");r.Append("SeedState=").Append(SeedState()).Append(" Seq=").Append(SeedSeq).Append(" Age=").Append(SeedAge).Append(" Vector=").Append(SeedVector).Append("\n\n");if(b==0){for(int i=1;i<=MAXB;i++)AppendBay(r,Bays[i],includeActions);}else AppendBay(r,Bays[b],includeActions);SetReport(r.ToString());Status="REG "+title+" report";}
void WriteStatusReport(int b){StringBuilder r=new StringBuilder();r.Append("[DCS STATUS]\nVersion=").Append(VERSION).Append("\nTag=").Append(Tag).Append("\nWave=").Append(Wave).Append("\nDeparture=F").Append(F(ClearForwardMeters)).Append('@').Append(F(ClearForwardSpeed)).Append(" Sep=").Append(F(SeparationMeters)).Append(" Fan=").Append(F(FanMeters)).Append("\n");AppendSeedStatus(r);r.Append("PerfLast=").Append(Hi).Append("/50000 ").Append(HiPhase).Append("\nPerfMax=").Append(HiCap).Append("/50000 ").Append(HiCapPhase).Append("\n\n");if(b==0){for(int i=1;i<=MAXB;i++)AppendBay(r,Bays[i],false);}else AppendBay(r,Bays[b],false);SetReport(r.ToString());Status="Status report";}
void WriteSeedReport(){StringBuilder r=new StringBuilder();r.Append("[DCS SEED STATUS]\nVersion=").Append(VERSION).Append("\n");AppendSeedStatus(r);r.Append("LastSeedMsg=").Append(LastSeedMsg).Append("\n");SetReport(r.ToString());Status="Seed status report";}
void AppendSeedStatus(StringBuilder r){r.Append("SeedState=").Append(SeedState()).Append("\nSeedSource=").Append(SeedSource).Append("\nSeedSeq=").Append(SeedSeq).Append("\nSeedAge=").Append(SeedAge).Append("\nSeedVector=").Append(SeedVector).Append("\n\n");}
void AppendBay(StringBuilder r,BayReg y,bool actions){if(y.N<1)return;if(y.Serial==""&&y.PbCount==0&&y.AnchorCount==0&&y.State==""&&y.Slot==0)return;r.Append("BAY").Append(B2(y.N)).Append("\n");r.Append("DPSState=").Append(y.DpsState).Append("\n");r.Append("Loaded=PJ").Append(B2(y.Slot)).Append("\n");r.Append("Next=PJ").Append(B2(y.NextSlot)).Append("\n");r.Append("Role=").Append(y.Role).Append("\n");r.Append("Short=").Append(y.Short).Append("\n");r.Append("Serial=").Append(y.Serial).Append("\n");r.Append("Departure=").Append(y.Departure).Append("\n");r.Append("Vector=").Append(y.Vector).Append("\n");r.Append("BayTaggedBlocks=").Append(y.AnchorCount).Append("\n");r.Append("InterfaceGridId=").Append(y.InterfaceGridId).Append("\n");r.Append("CandidatePBs=").Append(y.PbCount).Append("\n");r.Append("RejectedTaggedPBs=").Append(y.RejTaggedCount).Append("\n");r.Append("BayMerges=").Append(y.MergeCount).Append("\n");r.Append("SelectedPB=").Append(y.Pb!=null?y.Pb.CustomName:"-").Append("\n");r.Append("BayMerge=").Append(y.Merge!=null?y.Merge.CustomName:"-").Append("\n");r.Append("Accepted=").Append(y.Accepted?"YES":"NO").Append("\n");r.Append("ServiceDone=").Append(y.ServiceDone?"YES":"NO").Append("\n");r.Append("MergeOn=").Append(y.Merge!=null?(y.Merge.Enabled?"YES":"NO"):"-").Append("\n");if(y.CandDetail!=""){r.Append("UntaggedCandidates\n");r.Append(y.CandDetail);}if(y.RejDetail!=""){r.Append("RejectedTaggedPBs\n");r.Append(y.RejDetail);}r.Append("Clean=").Append(y.Clean?"YES":"NO").Append("\n");r.Append("Fault=").Append(y.Fault).Append("\n");r.Append("Heartbeat=").Append(y.Heartbeat?"YES":"NO").Append("\n");r.Append("State=").Append(y.State).Append("\n");r.Append("BAT=").Append(y.Bat).Append(" H2=").Append(y.H2).Append(" Age=").Append(y.Age).Append("\n");if(actions){r.Append("Actions\n");if(y.Clean){r.Append("  Write assignment\n  Enforce captive\n  Run BOOT\n  Wait heartbeat\n  Service: merge off after heartbeat\n  Connector remains locked\n");}else r.Append("  BLOCKED; review candidate list\n");}r.Append('\n');}
void SetReport(string body){Me.CustomData=CfgText()+"\n# <DCS_LAST_REPORT_BEGIN>\n"+body+"# <DCS_LAST_REPORT_END>\n";}

void EchoOut(){Echo("DCS V015");Echo("MODE "+Mode+" WAVE "+Wave);Echo("STATUS "+Status);Echo("DPS "+DpsPbs.Count+" LCD "+Lcds.Count);Echo("SEED "+SeedState()+" S"+SeedSeq+" A"+SeedAge);Echo("PERF "+(Hi/1000.0).ToString("0.0")+"K max "+(HiCap/1000.0).ToString("0.0")+"K "+HiCapPhase);}
void Upd(string p){int n=Runtime.CurrentInstructionCount;if(n>Hi){Hi=n;HiPhase=p;}if(n>HiCap){HiCap=n;HiCapPhase=p;}}

int BayNum(string s){string u=s.ToUpper();int p=u.IndexOf("BAY");if(p<0)return 0;return NumAt(u,p+3);}
int SlotFrom(string s){if(s==null)return 0;string u=s.ToUpper();int p=u.IndexOf("PJ");if(p>=0)return NumAt(u,p+2);return NumAt(u,0);}
int NumAt(string s,int p){int v=0;bool any=false;for(int i=p;i<s.Length;i++){char c=s[i];if(c>='0'&&c<='9'){v=v*10+(c-'0');any=true;}else if(any)break;}return any?v:0;}
string B2(int n){return n<10?"0"+n:n.ToString();}
bool Has(string s,string t){return s!=null&&s.ToUpper().Contains(t.ToUpper());}
string Val(string cd,string key){int i=cd.IndexOf(key);if(i<0)return"";i+=key.Length;int e=cd.IndexOf('\n',i);if(e<0)e=cd.Length;return cd.Substring(i,e-i).Trim();}
string ValSemi(string cd,string key){int i=cd.IndexOf(key);if(i<0)return"";i+=key.Length;int e=cd.IndexOf(';',i);if(e<0)e=cd.IndexOf('\n',i);if(e<0)e=cd.Length;return cd.Substring(i,e-i).Trim();}
int ToInt(string s){int v=0;int.TryParse(s,out v);return v;}
double ToD(string s){double v=0;double.TryParse(s,out v);return v;}
string F(double d){return d.ToString("0.##");}
string CleanTag(string t){return t.Replace("[","").Replace("]","");}

class BayReg{public int N,Age=9999,Bat=0,H2=0,Slot=0,NextSlot=0,AnchorCount=0,PbCount=0,RejTaggedCount=0,MergeCount=0,ServiceSeq=0;public long InterfaceGridId=0;public string DpsState="",Serial="",State="",Fault="",Role="DRONE",Short="D",Wave="A",Departure="",Vector="",CandDetail="",RejDetail="";public bool Heartbeat=false,Accepted=false,ServiceDone=false,Clean=false;public IMyProgrammableBlock Pb;public IMyShipMergeBlock Merge;public BayReg(int n){N=n;}public void ClearRuntime(){AnchorCount=PbCount=RejTaggedCount=MergeCount=0;InterfaceGridId=0;Pb=null;Merge=null;Clean=false;Fault="";CandDetail="";RejDetail="";}}
